### ISSUE TITLE
AD populating from FreeIPA(LDAP): LDAP: error code 34 while adding entry

### ISSUE THREAD

**Issue by 1trbot1** [lsc-project/lsc#101]
Please help, I followed the [tutorial](https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory) on LSC documentation but can't get it working.
When I'm starting synchronization task from FreeIPA LDAP to AD I'm receiving error for each user that found on FreeIPA.

For example

> Nov 27 12:59:44 - ERROR - Error while adding entry CN=haim,CN=Users,DC=ad,DC=beezz,DC=io in directory :javax.naming.InvalidNameException: CN=haim,CN=Users: [LDAP: error code 34 - 00002081: NameErr: DSID-03050EB3, problem 2003 (BAD_ATT_SYNTAX), data 0, best match of:
>         'CN=haim,CN=Users,DC=ad,DC=beezz,DC=io'
>  ]; remaining name 'CN=haim,CN=Users'
> Nov 27 12:59:44 - ERROR - Error while synchronizing ID CN=haim,CN=Users,DC=ad,DC=beezz,DC=io: java.lang.Exception: Technical problem while applying modifications to the destination
> dn: CN=haim,CN=Users,DC=ad,DC=beezz,DC=io
> changetype: add
> mail: haim@il.beezz.io
> sAMAccountName: haim
> unicodePwd:: IgBjAGgAYQBuAGcAZQBpAHQAIgA=
> givenName: Haim
> cn: Haim Omesi
> sn: Omesi
> objectclass: user
> objectclass: organizationalPerson
> objectclass: person
> objectclass: top
> userAccountControl: 512
> userPrincipalName: haim@il.beezz.io
> pwdLastSet: 0
> 

Here is my ` /etc/lsc/openldap2ad/lsc.xml` - 

```
#<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">
  <connections>
    <ldapConnection>
      <name>AD</name>
      <url>ldap://wsad.ad.beezz.io:389/DC=ad,DC=beezz,DC=io</url>
      <username>CN=Administrator,CN=Users,DC=ad,DC=beezz,DC=io</username>
      <password>password</password>
      <authentication>SIMPLE</authentication>
      <pageSize>1000</pageSize>
    </ldapConnection>
    <ldapConnection>
      <name>IPA</name>
      <url>ldap://localhost:389/dc=il,dc=beezz,dc=io</url>
      <username>uid=admin,cn=users,cn=accounts,dc=il,dc=beezz,dc=io</username>
      <password>password</password>
      <authentication>SIMPLE</authentication>
    </ldapConnection>
  </connections>
  <tasks>
    <task>
      <name>adUser</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>freeipa-source-service</name>
        <connection reference="IPA" />
        <baseDn>cn=users,cn=accounts,dc=il,dc=beezz,dc=io</baseDn>
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>cn</string>
          <string>description</string>
          <string>givenName</string>
          <string>mail</string>
          <string>sn</string>
          <string>uid</string>
          <string>userpassword</string>
        </fetchedAttributes>
        <getAllFilter><![CDATA[(objectClass=inetOrgPerson)]]></getAllFilter>
        <getOneFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={uid}))]]></getOneFilter>
        <cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={sAMAccountName}))]]></cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ad-dst-service</name>
        <connection reference="AD" />
        <baseDn>CN=Users,DC=ad,DC=beezz,DC=io</baseDn>
        <pivotAttributes>
          <string>sAMAccountName</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>cn</string>
          <string>description</string>
          <string>givenName</string>
          <string>mail</string>
          <string>objectclass</string>
          <string>pwdLastSet</string>
          <string>sAMAccountName</string>
          <string>sn</string>
          <string>unicodePwd</string>
          <string>userAccountControl</string>
          <string>userPrincipalName</string>
        </fetchedAttributes>
        <getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>
        <getOneFilter><![CDATA[(&(objectClass=user)(sAMAccountName={uid}))]]></getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>"CN=" + srcBean.getDatasetFirstValueById("uid") + ",CN=Users,DC=ad,DC=beezz,DC=io"</mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>
          <update>true</update>
          <delete>true</delete>
          <changeId>true</changeId>
        </conditions>
        <dataset>
          <name>objectclass</name>
          <policy>KEEP</policy>
          <createValues>
            <string>"user"</string>
            <string>"organizationalPerson"</string>
            <string>"person"</string>
            <string>"top"</string>
          </createValues>
        </dataset>
        <dataset>
         <name>sAMAccountName</name>
         <policy>KEEP</policy>
         <createValues>
          <string>srcBean.getDatasetFirstValueById("uid")</string>
         </createValues>
        </dataset>
        <dataset>
         <!-- userPrincipalName = uid + "@lsc-project.org" -->
         <name>userPrincipalName</name>
         <policy>FORCE</policy>
         <forceValues>
          <string>srcBean.getDatasetFirstValueById("uid") + "@il.beezz.io"</string>
         </forceValues>
        </dataset>
        <dataset>
         <name>userAccountControl</name>
         <policy>KEEP</policy>
         <createValues>
          <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
         </createValues>
        </dataset>
        <dataset>
         <!-- pwdLastSet = 0 to force user to change password on next connection --> 
         <name>pwdLastSet</name>
         <policy>KEEP</policy>
         <createValues>
          <string>"0"</string>
         </createValues>
        </dataset>
        <dataset>
          <!-- unicodePwd = "changeit" at creation (requires SSL connection to AD) -->
         <name>unicodePwd</name>
         <policy>KEEP</policy>
         <createValues>
         <string>AD.getUnicodePwd("changeit")</string>
         </createValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>

```

**Comment by coudot** [comment]
Your error is in the mainIdentifier, you are using uid instead of cn.

**Comment by 1trbot1** [comment]
Hi @coudot, thanks for your fast replay.
I used "cn" as main identifier at first place but I got error like this for each user in LDAP.

> Nov 28 12:34:29 - ERROR - Error while adding entry CN=Haim Omesi,CN=Users,DC=ad,DC=beezz,DC=io in directory :javax.naming.OperationNotSupportedException: 
> [LDAP: error code 53 - 0000001F: SvcErr: DSID-031A1262, problem 5003 (WILL_NOT_PERFORM), data 0
>  ]; remaining name 'CN=Haim Omesi,CN=Users'
> Nov 28 12:34:29 - ERROR - Error while synchronizing ID CN=Haim Omesi,CN=Users,DC=ad,DC=beezz,DC=io: java.lang.Exception: Technical problem while applying 
> modifications to the destination
>  Thu Nov 28 12:34:29 IST 2019
> dn: CN=Haim Omesi,CN=Users,DC=ad,DC=beezz,DC=io
> changetype: add
> mail: haim@il.beezz.io
> sAMAccountName: haim
> unicodePwd:: IgBjAGgAYQBuAGcAZQBpAHQAIgA=
> givenName: Haim
> cn: Haim Omesi
> sn: Omesi
> objectclass: user
> objectclass: organizationalPerson
> objectclass: person
> objectclass: top
> userAccountControl: 512
> userPrincipalName: haim@il.beezz.io
> pwdLastSet: 0

**Comment by coudot** [comment]
This is another issue. You need to use LDAPS to connect to AD if you want to be able to set the password value.

See https://lsc-project.org/documentation/howto/ssltls

**Comment by lucasdiedrich** [comment]
@coudot i can confirm that using starttls the freeipa is able to communicate with AD. But for some reason the error code above is prompting, and this:

javax.naming.OperationNotSupportedException: [LDAP: error code 53 - 0000052D: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0

Another thing, is ipaNthash the same thing as unicodePwd?

Thanks

**Comment by coudot** [comment]
Error 53 often mean that AD password policy refused your password because it was too complex.

And NT hash is not the same as unicodePwd. NT hash is a specific hash that is used by some MS products or by some VPN softwares.

**Comment by lucasdiedrich** [comment]
Thanks @coudot , yes, it was the password policy. So i was able to migrate some users, i just cant figureout how can i migrate the passwords also. thanks a lot.

**Comment by coudot** [comment]
Hope to have answered the question, please reopen if needed.
