### ISSUE TITLE
Persistent Search in AD2openDJ sync

### ISSUE THREAD

**Issue by gregorys100** [lsc-project/lsc#104]
Can someone please validate whether the following understanding is correct?

LSC source service enables event-based updates through LDAP Persistent Search Control. Where initially all the data is dumped and then followed by syncing only the changes made in the source.

If let's say, this connection breaks and is restarted, the service will repeat the process again by dumping all the data available at that point in time and then sync only the changes made in the source.

**Comment by coudot** [comment]
Yes, if connection breaks, the search will be reestablished and LSC will first read all entries before syncing only changes.

But with AD, persistent search can only be done on suffix with filter '(objectClass=*)'

**Comment by rouazana** [comment]
If I remember correctly with Syncrepl there are 2 cases:
- if connection to source breaks, LSC stops, allowing user to manually restart and so do a full resync
- if connection to destination breaks, LSC retries then display an error but does not stop

I'm not sure Persistent Search Control works in the same way.

**Comment by coudot** [comment]
It seems that the connection management is the same between Syncrepl and Persistent Search.
