### ISSUE TITLE
OU synchronization

### ISSUE THREAD

**Issue by gregorys100** [lsc-project/lsc#105]
I am trying to sync data from AD to openDJ.

Is it possible to sync the Organization Unit (OU)/Container data while maintaining the hierarchy within the OU?
Also, if a user switches OU, does that get synced too?

**Comment by coudot** [comment]
Yes, you need to create two tasks:
* A task to sync OU, and manage the hierarchy in the mainIdentifier expression
* A task to sync users, and set the OU of the user in the mainIdentifier

When a user will move form one OU to the other, LSC will first rename the entry, and at next task execution will apply modifications

**Comment by coudot** [comment]
Hope to have answered the question, please reopen if needed.
