### ISSUE TITLE
New JDBC Plugin which allows duplicate source keys created.

### ISSUE THREAD

**Issue by MSSputnik** [lsc-project/lsc#120]
I just want to inform you and the LSC community that I created a new Plug-in which support to handle the situation where a JDBC Data source has duplicate key values in the database table..
The plug-in allows to create a multi value hook to select the right entry from the source and write the chosen entry to the destination.

The plug-in can be found here: https://github.com/MSSputnik/lsc-multi-jdbc-src-service

**Comment by coudot** [comment]
We will add a documentation note about this plugin.

@MSSputnik we are planning to release 2.2 (master branch) in the next months. Could you see if your plugin works with this version?

**Comment by MSSputnik** [comment]
Thanks for this information. I will take care of this test for all of my plugins and give you feedback.

**Comment by coudot** [comment]
Added in https://lsc-project.org/documentation/start
