### ISSUE TITLE
Keeping old versions on Debian repository

### ISSUE THREAD

**Issue by rouazana** [lsc-project/lsc#121]
The Debian repository is only keeping the last version. https://lsc-project.org/debian/pool/main/l/lsc/

It can make some scripts break, for example if you build a Docker image on an exact (tested) LSC version.

Is there any reason to remove the old version? Cannot we keep the version history?

**Comment by coudot** [comment]
The answer will be the same as https://github.com/ltb-project/openldap-deb/issues/18

I use reprepro to manage Debian repositories, and should switch to aptly instead.

This would be done when moving from current server for a new one.

**Comment by coudot** [comment]
Done: https://lsc-project.org/debian/pool/main/l/lsc/
