### ISSUE TITLE
LSC configuration file loading failed

### ISSUE THREAD

**Issue by xantusDev** [lsc-project/lsc#123]
I am getting the following error when tried to do synchronization launch with  custom configurations : lsc -s all
OS :Windows 10
JDK:1.8
command     tool : cygwin64 terminal
The lsc.xml file is triying to be picked from the location  - **D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\bin\..\etc**
its actually present in **D:\DEVELOPER-TOOLS\lsc-2.1.5\etc**
_I was able to run the quick start project without any issues and was able to sync as well_
**Error:**
ERROR - Defined configuration location (D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\bin\..\etc) points to a non existing LSC configured instance. LSC configuration loading will fail !
Error: java.lang.RuntimeException: Defined configuration location (D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\bin\..\etc) points to a non existing LSC configured instance. LSC configuration loading will fail !
java.lang.RuntimeException: Defined configuration location (D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\bin\..\etc) points to a non existing LSC configured instance. LSC configuration loading will fail !
        at org.lsc.Configuration.setUp(Configuration.java:474)
        at org.lsc.Configuration.setUp(Configuration.java:456)
        at org.lsc.Launcher.run(Launcher.java:205)
        at org.lsc.Launcher.launch(Launcher.java:158)
        at org.lsc.Launcher.main(Launcher.java:141)

**Comment by coudot** [comment]
I think you are using lsc.bat. Could you try to adapt it witht his patch?
```
--- a/bin/lsc.bat
+++ b/bin/lsc.bat
@@ -42,7 +42,7 @@ REM  work out where LSC lives
 
 setLocal EnableDelayedExpansion
 
-for /f %%i in ("%0") do set LSC_HOME=%%~dpi..
+for /f %%i in ("%0") do set LSC_HOME=%%~dpi\..
 
 REM ====================================================================
 REM  Configuration

**Comment by xantusDev** [comment]
I tried applying the patch:
setLocal EnableDelayedExpansion
for /f %%i in ("%0") do set LSC_HOME=%%~dpi\..  in lsc file
_still the same issue._

not sure if D:\**cygdrive\d**\DEVELOPER-TOOLS\lsc-2.1.5\bin..\etc (The bold part) is ever treated by below code as valid path in windows:

lscConfigurationPath =" D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\bin..\etc" - in this case
if(lscConfigurationPath == null 
				|| ! new File(lscConfigurationPath).isDirectory()
				|| ( ! new File(lscConfigurationPath, JaxbXmlConfigurationHelper.LSC_CONF_XML).isFile()
						&& ! new File(lscConfigurationPath, PROPERTIES_FILENAME).isFile()))

**Comment by coudot** [comment]
Does D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\etc exists?

**Comment by xantusDev** [comment]
**D:\cygdrive\d\DEVELOPER-TOOLS\lsc-2.1.5\etc**  -doesn't exists as file path
valid path  : **D:\DEVELOPER-TOOLS\lsc-2.1.5\etc** - I am running command **bin/lsc -s all** from 
path **D:\DEVELOPER-TOOLS\lsc-2.1.5**
The source and destination is all configured in lsc.xml , but I am getting this issue.
As menioned above i a using windows 10 and cygwin terminal for running scripts.
![image](https://user-images.githubusercontent.com/19166514/83147061-cd0fbd00-a114-11ea-98a3-f7e27def6bf1.png)

**Comment by coudot** [comment]
Then edit by hand LSC_HOME in lsc.bat to match your installation

**Comment by xantusDev** [comment]
I was able to get it work by passing -f param to sync command.Thanks a lot

**Comment by coudot** [comment]
Indeed, this is the best solution!
