### ISSUE TITLE
How can I add multi value to some Attributes

### ISSUE THREAD

**Issue by youngtl** [lsc-project/lsc#128]
I'd like to add 'inetOrgPerson',  'shadowAccount'.. value to 'objectClass'.
How can I do it use LSC ?
Can anybody give some example ?

Does it work?
<dataset>
<name>objectClass</name>
<policy>KEEP</policy>
<createValues>
<string>"inetOrgPerson"</string>
</createValues>
<createValues>
<string>"shadowAccount"</string>
</createValues>
</dataset>

**Comment by coudot** [comment]
You just need to put multiple values in the dataset. See the sample configuration or any tutorial.

Example:
```
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"inetOrgPerson"</string>
            <string>"organizationalPerson"</string>
            <string>"person"</string>
            <string>"top"</string>
          </forceValues>
        </dataset>
```

**Comment by youngtl** [comment]
Thank you very much
