### ISSUE TITLE
LSC : SQLite + LDAP / ERROR - Unable to load configuration - cvc-complex-type.2.4.a: Invalid content

### ISSUE THREAD

**Issue by mehdah** [lsc-project/lsc#129]
Hi everyone !

I need to synchronize a local SQLite database from an LDAP server with the LSC Connector (Windows - 2.1.5). To do so, I first started by connecting my SQLite database using SQLite JDBC Driver (by following this tutorial https://www.sqlitetutorial.net/sqlite-java/sqlite-jdbc-driver/).

So I have an LDAP server as 'ldapSourceService' and a SQLite JDBC database as 'databaseDestinationService'. After modifying the connection information, I tried to start a synchronization via LSC. Unfortunately, I am faced with an error that I don't understand.

     ERROR - Unable to load configuration (org.lsc.exception.LscConfigurationException: Configuration exception: null)
     ...
     Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content found from the 'requestsNameForInsert' element. One of the values ​​'{"http://lsc-project.org/XSD/lsc-core-2.1.xsd":requestNameForList}' is expected.

I am currently using the sample provided in the download file and have not yet defined my own tasks. I am attaching a text file with the terminal return as well as the lsc.xml file that I use.

I just need help to understand this error and move on creating my own tasks.

Thank you !
Mehdi

[OUTPUT.txt](https://github.com/lsc-project/lsc/files/4891083/OUTPUT.txt)
[lsc_xml.txt](https://github.com/lsc-project/lsc/files/4891116/lsc_xml.txt)

**Comment by coudot** [comment]
Hello,

it seems our online documentation (https://lsc-project.org/documentation/latest/configuration/service/destinationsql) is not conform to the XML schema.

In the XML schema I see:
```xml
        <xsd:complexType name="databaseDestinationServiceType">
                <xsd:complexContent>
                        <xsd:extension base="serviceType">
                                <xsd:sequence>
                                        <xsd:element name="requestNameForList" type="xsd:string" />
                                        <xsd:element name="requestNameForObject" type="xsd:string" />
                                        <xsd:element name="requestsNameForInsert" type="valuesType" />
                                        <xsd:element name="requestsNameForUpdate" type="valuesType" />
                                        <xsd:element name="requestsNameForDelete" type="valuesType" />
                                </xsd:sequence>
                        </xsd:extension>
                </xsd:complexContent>
        </xsd:complexType>
```

So could you try this configuration:
```xml
      <databaseDestinationService>
        <name>jdbc-src-service</name>
        <connection reference="jdbc-dst-conn" />
       	<requestNameForList>getInetOrgPersonList</requestNameForList>
       	<requestNameForObject>getInetOrgPerson</requestNameForObject>
       	<requestsNameForInsert>
          <string>insertInetOrgPerson</string>
        </requestsNameForInsert>
       	<requestsNameForUpdate>
          <string>updateInetOrgPerson</string>
        </requestsNameForUpdate>
       	<requestsNameForDelete>
          <string>deleteInetOrgPerson</string>
        </requestsNameForDelete>
      </databaseDestinationService>

**Comment by mehdah** [comment]
Hi,

Thank you for your support Clement, it is now working well !
One last question : how can I be sure that the connection to the database is established ? 
When I launch LSC, this is what I get : 

```
juil. 09 17:02:20 - INFO  - Logging configuration successfully loaded from C:\Program Files\lsc\etc\logback.xml 
juil. 09 17:02:20 - INFO  - LSC configuration successfully loaded from C:\Program Files\lsc\etc\
juil. 09 17:02:20 - INFO  - Connecting to LDAP server ldap://10.241.6.60:389/ou=com,dc=test,dc=com as uid=back,ou=com,dc=test,dc=com
juil. 09 17:02:20 - INFO  - Starting sync for People
juil. 09 17:02:20 - ERROR - Cannot synchronize entry uid=Dupont,ou=users,ou=com,dc=test,dc=com: no matching object found in source
juil. 09 17:02:20 - ERROR - All entries: 1, to modify entries: 0, successfully modified entries: 0, errors: 1
```
Do you think it has something to do with the SQLite database connection ? 

Thank you !

**Comment by mehdah** [comment]
Thank you ! It is now working ;)

**Comment by coudot** [comment]
Thanks for the feedback, documentation fixed: https://lsc-project.org/documentation/latest/configuration/service/destinationsql
