### ISSUE TITLE
OU tree synchronization with pivot Transformation

### ISSUE THREAD

**Issue by ArnaudVOTA** [lsc-project/lsc#131]
Hi, 

I'm looking for a way to use LSC to periodically synchronize an AD with a complex hierarchy (that will change over time) to an OpenLDAP. 

I encounter an issue with the order of the OU synchronization, as described in this post from the mailing list : https://lists.lsc-project.org/pipermail/lsc-users/2012-April/000933.html

One simple way to resolve this problem would be to restart the script several times, but I don't consider this as a clean method for a production environment, as we may have several depth levels of hierarchy added in one time.

I found a comment on the mailing list that suggests that the addition of pivotTransformation in 2.2 version would make OU tree synchronization simplier; however I don't find a way to use it in my situation. Any help would be appreciated !

**Comment by coudot** [comment]
Hello,

by experience, reproducng `ou` hierarchy from AD into OpenLDAP is not the right way. We often sync users into a flat ou=users branch, and the `ou` hierarch into a dedicated ou=services branch. 

We can help you on the configuration.

**Comment by ArnaudVOTA** [comment]
Hello, 

A flat synchronization is already set up and work well, but unfortunately it is required in our situation to evolve to keep the hierarchy between the two directories. I precise that the OU hierarchy to synchronize only contains contacts

**Comment by coudot** [comment]
You should share your config if you want some help

**Comment by ArnaudVOTA** [comment]
For now we uses two LSC scripts periodically: one to synchronize OUs, another to synchronize contacts in their OU. The second one works well and don't need any modification.

The source AD is structured like this: 

|-- Contacts 
	|-- OUC1
		|-- Site 1
			- Contact A
			- Contact B
			- Contact C
		|-- Site 2
	|-- OUC2
		|-- Extented
			|-- Team A
				- Contact D
				- Contact E
			|-- Team B
				- Contact F
		|-- Limited
	|-- OUC3
	|-- OUC4
	... 
		
Each OU may contain undefined level of Sub-OU, that in the end contains contacts. The hierarchy is very heterogeneous, and we don't have control on what will be added in the future

I will add the lsc.xml we use later today if needed, it's just classical ou-synchronizing with filter on objectclass

**Comment by ArnaudVOTA** [comment]
Here is the config i'm using (sorry for the delay)

```
    <task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ldap-src"/>
          <baseDn>DC=Contacts</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="ldap-dst"/>
        <baseDn>dc=dest</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>dc</string>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=Contacts";
          replace = "dc=dest";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"dcObject"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>dn</name>
          <forceValues>
            <string>"dn"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>dc</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
```

**Comment by coudot** [comment]
Hello,

I don't any obvious solution, as LSC can't really know in which order create or rename entries to be sure the parent entry already exists.

What you can do is use create/modrdn conditions to skip entry and print a message when it has no parent.

**Comment by rouazana** [comment]
Hello,

I could remind that the FullDNJndiDstService was supposed to handle this case. Maybe you could have a look at it.

Regards,
Raphaël.

**Comment by ArnaudVOTA** [comment]
I finally wrote a bash script to handle OU-synchronisation before running LSC synchronisation.

An other idea would have been to use the conditions as you said; one option was to filter on the depth of the OU in order to synchronize depth by depth, but this solution needs to make one LSC script per depth level.

Thank you for the suggestion rouazana, unfortunately I'm pretty noobie in java and I don't have more time to spend to this issue... 

Thank you for your help 👍

**Comment by feeman89** [comment]
Is this the configuration that synchronizes openldap to AD?

**Comment by feeman89** [comment]
How to synchronize openldap OU to the configuration in AD
