### ISSUE TITLE
add operation changed to modify when policyType is FORCE

### ISSUE THREAD

**Issue by maxfieb** [lsc-project/lsc#134]
trying to sync opendj to AD server, ad server refuses attribute modify where the attribute to "replace" does not exist, in this case it wants the "add" operation as part of the modify. lsc seems to explicitly ignore adds when comparing beans ?

this might be different than other ldaps which more generously accept a modify with "replace" and the attibute does not exist (yet) and internally processes a modify as an add if needed.

in org.lsc.beans.BeanComparator there is : 

	case ADD_VALUES:
		LOGGER.debug("{} Adding attribute \"{}\" with values {}", new Object[]{logPrefix, attrName, toSetAttrValues});

		// BM: this breaks AD by arbitrarily changing add to modify (AD wont replace if attribute
		// BM: does not already exist, so the whole modify operation bombs out with error)

		// we use forceValues as we need to rename the attribute from source to destination
		if (modType != LscModificationType.CREATE_OBJECT && attrStatus == PolicyType.FORCE) {
			// By default, if we try to modify an attribute in
			// the destination entry, we have to care to replace all
			// values in the following conditions:
			// - FORCE action is used;
			// - A value is specified by the create_value parameter.
			// So, instead of add the attribute, we replace it.
			operationType = LscDatasetModificationType.REPLACE_VALUES;
		}
		// BM: this disables all add operations, needed for some AD destination ?

		mi = new LscDatasetModification(operationType, attrName, toSetAttrValues);
		break;

	case REPLACE_VALUES:
		if (attrStatus == PolicyType.FORCE) {
			if (isModified(dstBean, dstAttrValues, toSetAttrValues)) {
				LOGGER.debug("{} Replacing attribute \"{}\": source values are {}, old values were {}, new values are {}",
					new Object[]{logPrefix, attrName, srcAttrValues, dstAttrValues, toSetAttrValues});
					mi = new LscDatasetModification(operationType, dstAttr.getID(), toSetAttrValues);
			}
		} else if (attrStatus == PolicyType.MERGE) {
			// check if there are any extra values to be added
			Set<Object> missingValues = SetUtils.findMissingNeedles(dstAttrValues, toSetAttrValues);

			if (missingValues.size() > 0) {
				LOGGER.debug("{} Adding values to attribute \"{}\": new values are {}",
					new Object[]{logPrefix, attrName, missingValues});
				mi = new LscDatasetModification(LscDatasetModificationType.ADD_VALUES, dstAttr.getID(), missingValues);
			}
		}

	break;

Seems to me that if there is a ADD_VALUES, it will be changed to REPLACE_VALUES but none of the subsequent code
in case REPLACE_VALUES will not to the extra things (as the expression in the switch expression wont be re-evaluated)

case REPLACE_VALUES does different things to LscDatasetModification, so is this a bad thing? (things there wont happen). 

but even if this is not a big issue, changing add to modify like this will fail on AD with "Attribute does not exist" (code 16)
as trying replace a non-existing attribute (and that is what i am seeing in my example) is a hard error, the modify will fail

P.S. willing to help code this is somebody can assist getting a working build / test environment for jdk 1.8

**Comment by maxfieb** [comment]
I wonder if the following might do enough (replace unless the attr on the destBean is empty, then leave as add) :

// we use forceValues as we need to rename the attribute from source to destination
if (modType != LscModificationType.CREATE_OBJECT && attrStatus == PolicyType.FORCE) {
	// By default, if we try to modify an attribute in
	// the destination entry, we have to care to replace all
	// values in the following conditions:
	// - FORCE action is used;
	// - A value is specified by the create_value parameter.
	// - unless there are no existing values
	// So, instead of add the attribute, we replace it.
	if (dstBean.getDatasetById(attrName).size() > 0) {
		operationType = LscDatasetModificationType.REPLACE_VALUES;
	}
}

**Comment by rouazana** [comment]
it's strange, I never saw that on AD. On which attribute did it occur?

By the way changing "replace" to "add" is not always possible, because in some cases (think of password for example), you are not able to previously read the destination attribute and so to know if you have to update it or to add it.

**Comment by maxfieb** [comment]
It seems carLicence is the offending attribute that triggers the error (the logging does not say which attribute is at fault, but I removed attributes until the problem did not occur, it stopped when i commented carLicence from the lsc.xml).

It's syntax is DirectoryString but maybe MS add some extra validation or max length ?

**Comment by maxfieb** [comment]
actually I think the problem might be much simpler. i have <forceValues with javascript expression, a few of these evaluated to "" empty string and AD doesn't like that if you literally try to write that.

opendj does or can be configured to accept "" or null as "not present" to imply that there is no acrtual value.

so there perhaps is no way for a JS expression for <forceValues to say "not present" if there is no value to add in the case of AD, for AD the semantics are different, a workaround was to do :

<forceValues>
     <string>srcBean.getDatasetFirstValueById('description') ? srcBean.getDatasetFirstValueById('description').trim() : "NA"</string>
</forceValues>

**Comment by coudot** [comment]
> It's syntax is DirectoryString but maybe MS add some extra validation or max length ?

Seems there is no max size for this attribute: https://docs.microsoft.com/en-us/windows/win32/adschema/a-carlicense

**Comment by coudot** [comment]
> srcBean.getDatasetFirstValueById('description') ? srcBean.getDatasetFirstValueById('description').trim() : "NA"

Does this work?
```javascript
srcBean.getDatasetFirstValueById('description') ? srcBean.getDatasetFirstValueById('description').trim() : null

**Comment by maxfieb** [comment]
> > srcBean.getDatasetFirstValueById('description') ? srcBean.getDatasetFirstValueById('description').trim() : "NA"
> 
> Does this work?
> 
> ```js
> srcBean.getDatasetFirstValueById('description') ? srcBean.getDatasetFirstValueById('description').trim() : null 
> ```

Yes that works.
