### ISSUE TITLE
Wrong error message is displayed

### ISSUE THREAD

**Issue by remybezy** [lsc-project/lsc#137]
Hello,

I've recently setup a LSC.
I had this following Configuration :
- Source -> Active Directory from my client
- Destination -> OpenLDAP on my own server.

I've struggle a long time with this following error message :
```
 ERROR - Error opening the LDAP connection to the destination! (javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580])
```

I've lost a lot of time to figured out what was the issue on my Destination Server while everything was ok and working on my side but LSC was shouting errors.

Then got a feeling, I have modify the username/password used for the SOURCE connection and it worked !

You should display correctly the location of the error, in my case it was source and not destination.
That may be confusing.

Thanks !

Best Regard

**Comment by coudot** [comment]
This error message appears here: https://github.com/lsc-project/lsc/blob/v2.1/src/main/java/org/lsc/jndi/JndiServices.java#L467
We indeed don't know here if we are in source or destination.
