### ISSUE TITLE
 How to synchronize openldap OU organization to AD including contacts in OU ？

### ISSUE THREAD

**Issue by feeman89** [lsc-project/lsc#141]

**Comment by coudot** [comment]
Create an OpenLDAP to AD connector, see examples here: https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory

**Comment by feeman89** [comment]
Can this also synchronize ou？

**Comment by coudot** [comment]
You can synchronize any object, you need to create a task for each object type. You can create create a task to synchronize contacts.

**Comment by feeman89** [comment]
How to configure to synchronize openldap ou to ad

**Comment by feeman89** [comment]
The link you gave is for synchronizing contacts. Is there any specific example of synchronizing ou?

**Comment by feeman89** [comment]
<task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ldap-src"/>
          <baseDn>DC=Contacts</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="ldap-dst"/>
        <baseDn>dc=dest</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>dc</string>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=Contacts";
          replace = "dc=dest";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"dcObject"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>dn</name>
          <forceValues>
            <string>"dn"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>dc</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>



I use this configuration to synchronize 
the attribute not exits error

**Comment by feeman89** [comment]
I use this configuration to synchronize the property there is no error

**Comment by feeman89** [comment]
<task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ldap-src"/>
          <baseDn>DC=Contacts</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="ldap-dst"/>
        <baseDn>dc=dest</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>dc</string>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=Contacts";
          replace = "dc=dest";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>;</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"dcObject"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>dn</name>
          <forceValues>
            <string>"dn"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>dc</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>

**Comment by feeman89** [comment]
I use the above configuration to synchronize ou prompts attribute error

**Comment by feeman89** [comment]
一月 06 10:19:46 - ERROR - Error while adding entry  in directory :javax.naming.PartialResultException: [LDAP: error code 10 - 0000202B: RefErr: DSID-031007EF, data 0, 1 access points
        ref 1: 'com.int'
]; remaining name '/'
一月 06 10:19:46 - ERROR - Error while synchronizing ID : java.lang.Exception: Technical problem while applying modifications to the destination
一月 06 10:19:46 - ERROR - Error while synchronizing ID : java.lang.Exception: Technical problem while applying modifications to the destination
# Wed Jan 06 10:19:46 CST 2021



The following error is reported when synchronizing ou

**Comment by feeman89** [comment]
What does the above error mean?

**Comment by coudot** [comment]
Hello, see https://ldapwiki.com/wiki/LDAP%20Result%20Codes

Error 10 is a referral. Seems your are writing entries in the wrong place. Adapt your mainIdentifier expression to create entries in the good branch.

From my point of view, you don't need to add dc attribute and dcObject object class in your destination  entry.

**Comment by feeman89** [comment]
why i use srcBean.getDatasetFirstValueById("dn")

**Comment by feeman89** [comment]
is returned null

**Comment by coudot** [comment]
You can try:
```
srcBean.getMainIdentifier();
```

See https://lsc-project.org/javadoc/2.1-SNAPSHOT/org/lsc/beans/LscBean.html#getMainIdentifier--

**Comment by feeman89** [comment]
this return like this ou=people,dc=com ,but i wan't OU=peple,DC=com

**Comment by feeman89** [comment]
because is return error

**Comment by feeman89** [comment]
一月 06 17:52:04 - ERROR - Error while adding entry cn=douzi ,cn=douzi,ou=people,dc=service,dc=com,dc=int in directory :javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-0310020A, problem 2001 (NO_OBJECT), data 0, best match of:
        'OU=people,DC=service,DC=com,DC=int'

**Comment by feeman89** [comment]
i'am sorry, how can't i sync openldap password to ad ?

**Comment by soisik** [comment]
see #142
