### ISSUE TITLE
 How to synchronize openldap password to ad?

### ISSUE THREAD

**Issue by feeman89** [lsc-project/lsc#142]

**Comment by coudot** [comment]
Read https://lsc-project.org/documentation/howto/activedirectory#password_synchronization

**Comment by feeman89** [comment]
thank you， my english is pool , my openldap use ssha method encryption , it can sync to ad ?

**Comment by coudot** [comment]
No it will not work

**Comment by feeman89** [comment]
if i use md5 method encryption , can it work?

**Comment by feeman89** [comment]
thank you very much , if i use md5 encryption method in openldap , it can sync to ad ?

**Comment by feeman89** [comment]
or only  clear text can sync to ad ?

**Comment by coudot** [comment]
Yes only cleartext

**Comment by feeman89** [comment]
thank you

**Comment by feeman89** [comment]
do you know haw to configure openldap default use cleartext method entryption method ?

**Comment by coudot** [comment]
cleartext is the default

**Comment by feeman89** [comment]
no , i use the docker image "osixia/docker-openldap"  ssha is the default

**Comment by feeman89** [comment]
how sync cleartext password to ad

**Comment by feeman89** [comment]
i change my openldap password to cleartext , but it steal not work

**Comment by feeman89** [comment]
<dataset>
          <name>userPrincipalName</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("uid") + "@service.com.int"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <createValues>
            <string>"user"</string>
            <string>"person"</string>
            <string>"top"</string>
          </createValues>
        </dataset>
        <dataset>
          <name>userAccountControl</name>
          <policy>KEEP</policy>
          <createValues>
            <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
          </createValues>
        </dataset>
        <dataset>
          
          <name>unicodePwd</name>
          <policy>KEEP</policy>
          <createValues>
            <string>AD.getUnicodePwd(srcBean.getDatasetFirstValueById("userPassword"))</string>
          </createValues>
        </dataset>
        <dataset>
          <name>pwdLastSet</name>
          <policy>KEEP</policy>
          <createValues>
            <string>"-1"</string>
          </createValues>
        </dataset>


this is my part configure

**Comment by coudot** [comment]
If you use KEEP policy and createValues markup, the value will only be set when creating new entries.

Try with FORCE policy and forceValues markup.

**Comment by feeman89** [comment]
<name>samAccountName</name>
          <policy>KEEP</policy>
          <createValues>
            <string>js:srcBean.getDatasetFirstValueById("uid")</string>
          </createValues>
        </dataset>
        <dataset>
          <name>userPrincipalName</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("uid") + "@service.com.int"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"user"</string>
            <string>"person"</string>
            <string>"top"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>userAccountControl</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
          </forceValues>
        </dataset>
        <dataset>
          
          <name>unicodePwd</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>AD.getUnicodePwd(srcBean.getDatasetFirstValueById("userPassword"))</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>pwdLastSet</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"-1"</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>


i use FORCE policy and forceValues markup. but is still not work, the password can't sync

**Comment by coudot** [comment]
Check that you are using SSL to connect to AD, and that unicodePwd and userPassword are definined in dest and src fetchedAttributes

Use debug loglevel in logback.xml to get more traces

**Comment by feeman89** [comment]
it work fine ,thank you!
