### ISSUE TITLE
Create works but Syncing Existing Accounts Does not.

### ISSUE THREAD

**Issue by GSACRD-TECH** [lsc-project/lsc#144]
Just Working on getting the system working for all the areas we need but I can only create accounts.
The system once the accounts are created are not syncing on the UID and the sAMAccountName but on the distinguishedName Which would work but has to be encapsulated with quotes as an ldapsearch will fail with the same information.

how would someone get the sync function to encapsulate the distinguishedName that is being driven by the <mainIdentifier>
[lsc.txt](https://github.com/lsc-project/lsc/files/6185363/lsc.txt)

Any hint would be great.

**Comment by soisik** [comment]
Hi,

Could you share the errors you're getting, so we fully understand your issue.

Just guessing, you could try to escape mainIdentifier CN with javax.naming.ldap.Rdn.escapeValue(srcBean.getDatasetFirstValueById("cn")).

The sync function uses the getOneFilter from destination service to retrieve a matching entry, right now it searches for samAccountName=uid (the uid from openldap), which should work.

**Comment by GSACRD-TECH** [comment]
Mar 23 08:37:16 - ERROR - Error while modifying entry CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca in directory :javax.naming.OperationNotSupportedException: [LDAP: error code 53 - 00002077: SvcErr: DSID-031903D3, problem 5003 (WILL_NOT_PERFORM), data 0
]; remaining name 'CN=Sean Douglas'
Mar 23 08:37:16 - ERROR - Error while synchronizing ID CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca: java.lang.Exception: Technical problem while applying modifications to the destination
# Tue Mar 23 08:37:16 MDT 2021
dn: CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca
changetype: modify
replace: unicodePwd
unicodePwd:: IgAiAA==
-
delete: userAccountControl
-
delete: pwdLastSet
-

Mar 23 08:37:16 - ERROR - All entries: 992, to modify entries: 992, successfully modified entries: 0, errors: 992

**Comment by GSACRD-TECH** [comment]
I do believe that the issue arises out of the CN value that has a space in it and breaks the parsing of the entry variable.

**Comment by GSACRD-TECH** [comment]
I have everything setup withthe sAMAccountName, Creating accounts is no problem updating them is. The system appears to be attempting to sync on the mainIdentity"cn=" + srcBean.getDatasetFisrtValueById("cn") + ".CN=Users,DC=domain,DC=TLD" 
what will i need to update on the mainIdentity strucutre to get this to syncronize on sAMAccountName.

**Comment by soisik** [comment]
I think the error is more likely caused by the AD refusing to delete userAccountControl or/and pwdLastSet attributes.

Remove these attributes from fetched attributes if you don't want to set them up, or provide a value for them in dataset for creation, (example taken from https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory
```
<dataset>
     <name>userAccountControl</name>
     <policy>KEEP</policy>
     <createValues>
      <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
     </createValues>
    </dataset>
    <dataset>
     <!-- pwdLastSet = 0 to force user to change password on next connection --> 
     <name>pwdLastSet</name>
     <policy>KEEP</policy>
     <createValues>
      <string>"0"</string>
     </createValues>
    </dataset>
    <dataset>
``` 

Also, unicodePwd with a <policy>FORCE</policy> means the password will be updated everytime you run LSC, because LSC cannot read clear password from AD. As a result, users will not be able to change their password in AD. It also implies that the password is stored as clear text in OpenLDAP for LSC to send the right value. Let us know what is your set up and what you want to achieve with password management if this is not what you are trying to do.

**Comment by GSACRD-TECH** [comment]
Thanks but I don't have anything set for setting the AD user account control. Currently We have and LDAP server that we have special accounts that allow for clear password reading and this will be updated more specifically one I have the sync working. 
will perform the bind check to see if the password has changed. We do not use AD as our primary login structure as we are mostly and opensource environment. We need an AD server for one service that requires an AD sync.

**Comment by soisik** [comment]
If you not intend to set or update userAccountControl or pwdLastSet then you should remove them from the destination fetchedAttributes .

```
		<ldapDestinationService>
			<name>ad-dst-service</name>
			<connection reference="ad-dst-conn" />
			<baseDn>CN=Users,DC=gsacrd,DC=ab,DC=ca</baseDn>
			<pivotAttributes>
				<string>sAMAccountName</string>
			</pivotAttributes>
			<fetchedAttributes>
				<string>cn</string>
				<string>description</string>
				<string>givenName</string>
				<string>mail</string>
				<string>objectClass</string>
-				<string>pwdLastSet</string>
				<string>sAMAccountName</string>
				<string>unicodePwd</string>
				<string>sn</string>
-				<string>userAccountControl</string>
				<string>userPrincipalName</string>
			</fetchedAttributes>
			<getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>
			<getOneFilter><![CDATA[(&(objectClass=user)(sAMAccountName={uid}))]]></getOneFilter>
		</ldapDestinationService>
```

If they are listed here, LSC will try and match them with any attribute from source. If they are not in a dataset, LSC try to match them by name, and not finding them in source, it assumes they need to be removed. AD creates them automatically on user creation and it seems very wrong to try and delete them.

**Comment by GSACRD-TECH** [comment]
Okay that is the issue So how would one go about setting those attributes?

**Comment by coudot** [comment]
See some examples here: https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory

**Comment by GSACRD-TECH** [comment]
Okay so the reason for the issue was that I had loaded the variables and then did nothing with them. Is that correct?

**Comment by soisik** [comment]
It is correct. From documentation https://lsc-project.org/documentation/latest/configuration/service/destinationldap:
fetchedAttributes: mandatory, this list of string values contains all the attributes that will be synchronized according to the source object and the synchronization options.

These values can be set at creation using `<policy>KEEP</policy>` and `<createValues>`, to prevent any updates.

**Comment by GSACRD-TECH** [comment]
Okay so have all my accounts but they are all disabled on the AD server and this does not work 
` <dataset>
                                <name>userAccountControl</name>
                                <policy>FORCE</policy>
                                <forceValues>
                                        <string>AD.userAccountControlSet("0", AD.UAC_UNSET_ACCOUNTDISABLE)</string>
                                </forceValues>
                        </dataset>
`
This is the error. 
`Mar 23 13:27:16 - ERROR - Error while synchronizing ID {uid=sdouglas}: org.lsc.exception.LscServiceException: java.lang.ClassCastException: Cannot cast java.lang.Integer to [Ljava.lang.String;
Mar 23 13:27:16 - ERROR - All entries: 992, to modify entries: 0, successfully modified entries: 0, errors: 992
`

**Comment by coudot** [comment]
Check how you use the userAccountControlSet method, the second parameter is an array.

Try:
```xml
    <dataset>
     <name>userAccountControl</name>
     <policy>FORCE</policy>
     <forceValues>
      <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
     </forceValues>
    </dataset>

**Comment by GSACRD-TECH** [comment]
Not that gives this
`Mar 23 13:48:06 - ERROR - Error while modifying entry CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca in directory :javax.naming.OperationNotSupportedException: [LDAP: error code 53 - 0000052D: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0
]; remaining name 'CN=Sean Douglas'
Mar 23 13:48:06 - ERROR - Error while synchronizing ID CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca: java.lang.Exception: Technical problem while applying modifications to the destination
# Tue Mar 23 13:48:06 MDT 2021
dn: CN=Sean Douglas,CN=Users,DC=gsacrd,DC=ab,DC=ca
changetype: modify
replace: unicodePwd
unicodePwd:: IgAxADQANAAwADYAIgA=
-
replace: userAccountControl
userAccountControl: 2
-

Mar 23 13:48:06 - ERROR - All entries: 992, to modify entries: 992, successfully modified entries: 0, errors: 992
`

**Comment by coudot** [comment]
Error 53 means you are not allowed to update the password. Main causes:
* You are not using LDAPS
* Password is too weak

**Comment by GSACRD-TECH** [comment]
Using ldaps and password complexity is turned off

**Comment by GSACRD-TECH** [comment]
I can sync the password and then enable the account and I can access the user information which is nothing because no groups have been set.

**Comment by GSACRD-TECH** [comment]
Just cannot get the account to be enable from the script.

**Comment by GSACRD-TECH** [comment]
You are correct the Server is rejecting the password.

**Comment by GSACRD-TECH** [comment]
Okay corrected that but the accounts are still disabled.

**Comment by soisik** [comment]
I guess something went wrong with the data during trials and AD have disabled accounts. Maybe try to delete all the account to start with a fresh set up,  or try this to unset account disable on all entries to be updated:
```
<dataset>
 <name>userAccountControl</name>
 <policy>FORCE</policy>
 <createValues>
  <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
 </createValues>
 <forceValues>
  <string>AD.userAccountControlSet(dstBean.getDatasetFirstValueById('userAccountControl'), [AD.UAC_UNSET_ACCOUNTDISABLE])</string>
 </forceValues>
</dataset>
```    
If you enable debug in logback.xml, you will see the userAccountControl original value.

**Comment by GSACRD-TECH** [comment]
Thanks for all your help and need info on this error. 
'ERROR - Error while adding entry cn=Kenneth Haas,CN=Users,DC=gsacrd,DC=ab,DC=ca in directory :javax.naming.directory.NoSuchAttributeException: [LDAP: error code 16 - 00000057: LdapErr: DSID-0C091082, comment: Error in attribute conversion operation, data 0, v3839^@]; remaining name 'cn=Kenneth Haas'
Mar 24 14:37:14 - ERROR - Error while synchronizing ID cn=Kenneth Haas,CN=Users,DC=gsacrd,DC=ab,DC=ca: java.lang.Exception: Technical problem while applying modifications to the destination'

When I first setup the lsc.xml file all the datasets were set to FORCE now I am just tyring to use KEEP and this is the eror I get. Not sure where to look. Any Hints.

**Comment by coudot** [comment]
NoSuchAttributeException means you try to set an attribute which does not exist. What is the content of the entry your try ti add?

**Comment by GSACRD-TECH** [comment]
Same as before I delete a user that added before and then switched all the dataset's to KEEP. Now it gives error that it cannot create. 
Do you want another copy of the LSC.XML

**Comment by coudot** [comment]
Set DEBUG in logback.xml

**Comment by GSACRD-TECH** [comment]
Not getting any more details than I had before?

**Comment by soisik** [comment]
Please show your new lsc.xml and any log that appears before the error.

As clement said, NoSuchAttributeException means you try to set an attribute which does not exist in AD.

**Comment by GSACRD-TECH** [comment]
Here is the current LSC.XML and the log.
[lsc.txt](https://github.com/lsc-project/lsc/files/6205479/lsc.txt)
[log.txt](https://github.com/lsc-project/lsc/files/6205481/log.txt)

**Comment by soisik** [comment]
Remove objectClass from fetchedAttributes in ldapSourceService, you don't need it. Also it seems that having this attribute declared in source ends up pushing the source objectClass values instead of the ones declared in your dataset. This seems to be a bug, https://lsc-project.org/documentation/latest/configuration/syncoptions#functionality_matrix says that keep policy with createValues will ignore source values when adding a new entry.

Also, this doesn't make sense, you cannot unassign a control on a 0 value:

```
<dataset>
    <name>userAccountControl</name>
    <policy>KEEP</policy>
    <createValues>
        <string>AD.userAccountControlSet( "0", [AD.UAC_UNSET_ACCOUNTDISABLE])</string>
    </createValues>
</dataset>
```

It should be AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT]) for creating an active account.

**Comment by GSACRD-TECH** [comment]
I have removed reference to that structure as I thought that may be the issue but it still produced the same error. 
Will tinker with that structure to see if I can get it to add. Thanks

**Comment by GSACRD-TECH** [comment]
Using the AD.UAC_SET_NORMAL_ACCOUNT does not make the account disabled. The issue was that the objectClass needed to be FORCE as it was trying to find openLdap value in the AD server.

Will this command prevent the sync from removing the accounts on the AD server?
` <cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={sAMAccountName})!(uid=Administator)!(uid=Guest)!(uid=DefaulAccount)!(uid=krbtgt)!(uid=syncread))]]></cleanFilter>`

**Comment by soisik** [comment]
As I said in my previous message,  if you remove the objectClass reference from the fetchedAttribute of your source (you don't need to load openldap objectClass values), you can keep setting your objectClass attribute using createValues. 

The source cleanFilter is used against the source, to match each record retrieved by the destination getAllFilter. If you want to prevent some AD records to be removed by the clean task, then they should not be retrieved by the destination getAllFilter, and thus will be ignored:

```
<getAllFilter><![CDATA[(&(objectClass=user)(!(sAMAccountName=Administator))(!(sAMAccountName=Guest))(!(sAMAccountName=DefaulAccount))(!(sAMAccountName=krbtgt))(!(sAMAccountName=syncread)))]]></getAllFilter>
```

**Comment by GSACRD-TECH** [comment]
Still have not tested the clean up process with the suggestion as I just finished banging my head against a wall with why 5 accounts were not syncing. How can I put an if statement into the sync process to have the statement check for null on the employeeNumber?

**Comment by GSACRD-TECH** [comment]
Can my lsc.xml file have multiple tasks or do i have to build separate files for each task I need to perform.

attached is the current lsc.xml
[lsc.txt](https://github.com/lsc-project/lsc/files/6208252/lsc.txt)

**Comment by soisik** [comment]
> How can I put an if statement into the sync process to have the statement check for null on the employeeNumber?

You can write something like this:

```
<string>js:
	var employeeNumber = srcBean.getDatasetFirstValueById("employeeNumber");
	var unicodePwd = '';
	if (employeeNumber != '') {
		unicodePwd = AD.getUnicodePwd(employeeNumber);
	}
	unicodePwd
</string>
```

> Can my lsc.xml file have multiple tasks or do i have to build separate files for each task I need to perform.

Yes, your file can contains multiple tasks. 
You can choose which one to execute with option -s <task-name> or -s all to execute them all in task name alphabetical order.
