### ISSUE TITLE
Publish Javadoc

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#15]
We need to create a task that will publish javadoc for each LSC release.

I just uploaded the latest javadoc on the server for the moment: https://lsc-project.org/javadoc/2.1-SNAPSHOT/

**Comment by rouazana** [comment]
maybe https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/ ?

**Comment by coudot** [comment]
I created a script on LSC server to rebuild javadoc each night.

All versions are available here: https://lsc-project.org/javadoc/

The `latest` link is a symlink to 2.1, it will then be changed to 2.2
