### ISSUE TITLE
SCIM plugin

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#160]
@giuseppeamato  has coded a SCIM plugin: https://github.com/giuseppeamato/lsc-scim-plugin

We should see if it can be added as official plugin

**Comment by rouazana** [comment]
This is really nice!

There are some tests (even if some are missing), the code is pretty good, it's implementing a standard, so I'm totally in favor of integrating it as an official plugin.

**Comment by coudot** [comment]
@giuseppeamato would you be ok to move your plugin to LSC organization in github?

**Comment by coudot** [comment]
SCIM plugin is for the moment listed in non official plugins
