### ISSUE TITLE
Add new official plugins in doc

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#164]
Candidates:
* James
* Microsoft Graph API
* FusionDirectory

Maybe remove these ones (tag them as community):
* NIS
* OBM

**Comment by bilbo-the-hobbit** [comment]
hello @coudot 

its FusionDirectory not Fusion Directory :smile: 

Cheers

**Comment by coudot** [comment]
@bilbo-the-hobbit fixed in the comment.

I'm happy that you reacted to this issue. I know we already had this discussion in private, but other developers would like to know when the REST API will be officialy released, so we can officially propose this LSC plugin. Could you reassure us about it?

**Comment by bilbo-the-hobbit** [comment]
hello

we aim on our second try :smile: at releasing FusionDirectory 1.4 in October, i will change the roadmap accordingly on FusionDirectory website

:smiley:

**Comment by coudot** [comment]
See https://github.com/lsc-project/lsc-website/issues/1

LSC Fusion Directory plugin has been officially published even if Fusion Directory 1.4 is still not released. See https://github.com/lsc-project/lsc-fusiondirectory-plugin/releases/tag/v1.0
