### ISSUE TITLE
Use relax rules control when performing updates

### ISSUE THREAD

**Issue by soisik** [lsc-project/lsc#165]
Some attributes (entryUUID, createTimestamp ...) cannot be updated like normal attributes, as they are protected operational attributes. 

Since Openldap supports [relax rules control](https://tools.ietf.org/html/draft-zeilenga-ldap-relax-03), we should add an option in a connection configuration to activate this control and be able to update operational attributes. 

Our use case is to keep identical entryUUID while migrating to a new LDAP directory (some apps use this attribute to link ldap entry to their local user/group), and keep historical information.

**Comment by davidcoutadeur** [comment]
For information and if I remember correctly, some attributes, even if used with relax control, are not updatable

**Comment by soisik** [comment]
PR merged into v2.1 and master
