### ISSUE TITLE
Cannot run tests because of failing OpenDJ dependency

### ISSUE THREAD

**Issue by foxalfabravo** [lsc-project/lsc#17]
Running tests using mvn -Popendj test fails in both environment I tested (Linux from command line, Windows from Eclipse) because of OpenDj dependency

I don't know if it's related to the new forgerock policy or to the JDK (8). 

In Linux case I have a certificate problem : 
` ..... , org.forgerock.ce.opendj:opendj-server:jar:2.6.2 (compile)]: Failed to read artifact descriptor for org.forgerock.ce.opendj:opendj-server:jar:2.6.2: Could not transfer artifact org.forgerock.ce.opendj:opendj-server:pom:2.6.2 from/to lsc-site (http://lsc-project.org/maven): hostname in certificate didn't match: <lsc-project.org> != <auth.oodo.net> OR <auth.oodo.net> OR <awstats.oodo.net> OR <cadeaux.oodo.net> OR <fd.oodo.net> OR <manager.oodo.net> OR <oc.oodo.net> OR <owncloud.oodo.net> OR <photos.oodo.net> OR <phpmyadmin.oodo.net>`

Using Eclipse :
`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project lsc-core: Could not resolve dependencies for project org.lsc:lsc-core:jar:2.2-SNAPSHOT: Failed to collect dependencies at org.forgerock.ce.opendj:opendj-server:jar:2.6.2

I saw in mailing list that you managed to mitigate the issue by using local cache/repository. Could you share the method?
`

**Comment by coudot** [comment]
Hello,

it seems to work with latest patch from @soisik : 

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building LDAP Synchronization Connector 2.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://download.java.net/maven/2/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: http://maven.forgerock.org/repo/community/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: http://download.oracle.com/maven/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: http://reflections.googlecode.com/svn/repo/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: http://lsc-project.org/maven/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: http://maven.burtsev.net/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
Downloading: https://repo.maven.apache.org/maven2/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.pom
[WARNING] The POM for org.forgerock.ce.opendj:opendj-server:jar:2.6.2 is missing, no dependency information available
Downloading: http://download.java.net/maven/2/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.jar
Downloading: http://maven.forgerock.org/repo/community/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.jar
Downloaded: http://maven.forgerock.org/repo/community/org/forgerock/ce/opendj/opendj-server/2.6.2/opendj-server-2.6.2.jar (10174 KB at 2838.5 KB/sec)
```

Check which repository is used in pom.xml.

Note that Travis build are working too: https://travis-ci.org/lsc-project/lsc

**Comment by soisik** [comment]
I cannot reproduce your issue when I remove opendj dependency from my local repository, so it's somehow caused by your specific environment. 
Can you reach http://maven.forgerock.org/repo/community from your workstation ?
Do you have some repositories set up in your maven settings.xml, or maybe you're using a company nexus as a proxy? My guess : You may have to ask you nexus admin to add http://maven.forgerock.org/repo/community to nexus.
Also please provide complete logs for linux maven build.

**Comment by foxalfabravo** [comment]
First about your questions : 
1) access to forgerock repo : yes
2) No settings.xml
3) No nexus
4) Environment : Win10 - Eclipse/Dos command line/Ubuntu bash 
5) Full cleanup of .m2 cache & target directory before each try
=> everything fails (command line logs attached) 

I guess it's win10 related so I won't bother you until I find a solution (and it's not AV / MITM related)

[lsc.zip](https://github.com/lsc-project/lsc/files/1006164/lsc.zip)

**Comment by foxalfabravo** [comment]
Update : 
Upgrading jdk1.8.0_65 to jdk1.8.0_131 did it for windows command line and Eclipse, I guess it was related to LetsEncrypt certificate not accepted before 8u101
