### ISSUE TITLE
The lsc user created by the debian package should ever be a system user

### ISSUE THREAD

**Issue by jojo2024** [lsc-project/lsc#18]
In lsc.postinst script provided by lsc 2.1.4-1 package, lsc user is created with the "useradd lsc" command.
If nss_ldap is configured to map ldap user, the lsc user can obtain an uidNumber in the "ldap range" instead of the "system range".
Adding the "--system" option can avoid this problem.

**Comment by kasimon** [comment]
Also keep in mind that this fix would only affect new installations, not upgrades. I would recommend adding a note to the release notes or README.Debian that it may be better to purge and reinstall the package to fix the lsc user. I don't think there's a safe way to retroactively "systemize" an already created user account.

**Comment by coudot** [comment]
Merged in 2.1 and applied in master with cherry-pick
