### ISSUE TITLE
JDK 11 support

### ISSUE THREAD

**Issue by jbe-dw** [lsc-project/lsc#187]
Hello,

Can you tell me if we can install LSC with Java 11 ? It is not clearly written and we would like to use the distribution packages (openjdk-11-jdk).

We use some JS to sync from LDAP now.

Regards
Jerome

**Comment by coudot** [comment]
The support  for JDK 11 will be in 2.2, see https://github.com/lsc-project/lsc/pull/94

**Comment by jbe-dw** [comment]
Thanks for the quick reply. Do you have an estimated release date for 2.2 ?

**Comment by coudot** [comment]
No, but we are looking for help!

**Comment by jbe-dw** [comment]
I wish I could but I have no skill in Java !

I let you decide if you close the issue, as you answered me.

Thank you !
