### ISSUE TITLE
Very lacking documentation - Can't figure out how to do a simple thing

### ISSUE THREAD

**Issue by orenshaniathuji** [lsc-project/lsc#189]
Hi All,

I am really very sorry that this text looks more like ranting than like an issue, but I am really out of my wits here.

I am trying do do a very simple thing with LSC:

We have an OpenLDAP server (read-only) and an AD server. We want to periodically sync user data from the LDAP server into AD.

I was able to populate the AD once, with data from OpenLDAP by [following this procedure](https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory). However, when I run LSC again it tries to create, not update, the existing records and obviously fails.

I can understand why is that - The config file I am using is for populating, not updating the AD server. What I can't figure out is how to change the configuration. I've tried my best to figure that out from the docs, and by googling up just about everything about LSC, and I can't figure out what is supposed to be a very basic thing.

I am pretty sure that if someone will explain to me just the main principle: How do you tell LSC to add new records and update existing records in the AD, I will be able to figure out the details. So please help! I am opening this as an issue, because I am sure I am not the only one who can't figure that up...

Many thanks,

Oren

**Comment by coudot** [comment]
Hello,

we saw your question on the mailing list: https://mail.ow2.org/wws/arc/lsc-users/2022-06/msg00000.html

Someone of the community will answer you when we have time. Please do not duplicate the question here.
