### ISSUE TITLE
Hook / Trigger system for add/delete/modify/modrdn

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#193]
A useful feature would be to be able to call a script (like it is done in executable plugin) but when an entry is added/modified/deleted/...

A common use case is to send a mail to user when the entry is created.

**Comment by davidcoutadeur** [comment]
Seems all good to me.

For now:
- only a posthook is added
- call the script with 3 arguments: entry identifier (DN), operation (create, update, delete, changeid), operations
- operations is a json structure representing the operations on the entry

TODO: if/when merged, it is required to update the documentation to describe the behavior. (on the master branch of the documentation corresponding to 2.2)

**Comment by davidcoutadeur** [comment]
The test is missing, I am working on it.

**Comment by davidcoutadeur** [comment]
The MR has been merged.

The documentation is updated here: https://github.com/lsc-project/documentation/commit/613e3d9104f6e6b794998cb019c0169c4fb2c94a

All seems ok.

**Comment by davidcoutadeur** [comment]
Small test regression. I don't know how I could not have noticed before. Should be solved by 62eda9f5
