### ISSUE TITLE
java files autogenerated by JAXB are commited to git

### ISSUE THREAD

**Issue by artlog** [lsc-project/lsc#199]
`find src  -name '*.java' | xargs grep -e '\(Généré le\)\|\(Generated on\)' | wc -l `
46

source file for autogeneration main/resources/schemas/lsc-core-2.2.xsd  is enough for those files

**Comment by artlog** [comment]
all generated file are in src/main/java/org/lsc/configuration
but some file in  src/main/java/org/lsc/configuration are not autogenerated.

PivotTransformationServiceType.java is told autogenerated but is not anymore, it seems unused and a remaining file from commit  9d3431e505a5341d13f75141dc99e58ede16458b New feature: pivot transformation (references #756).

PropertiesConfigurationHelper.java XsdForLscComparator.java JaxbXmlConfigurationHelper.java and LscConfiguration.java are the one to keep.

**Comment by coudot** [comment]
@soisik We should revert this change and try to follow @rouazana recommandation (put generated java file in target, or at least in src/generated)
