### ISSUE TITLE
Too many entries returned

### ISSUE THREAD

**Issue by wanglongsxr** [lsc-project/lsc#209]
In our organizational hierarchy, the situation of "using the same name in two departments" will cause us to encounter such problems when we use lsc synchronization (AD domain synchronization to openldap) organization:
`
ERROR - Too many entries returned (base: "OU=aaa,DC=abc,DC=com", filter: "(& (objectClass=organizationalUnit) (ou=测试部) )")
ERROR - Error while synchronizing ID {ou=测试部}: org.lsc.exception.LscServiceException: javax.naming.SizeLimitExceededException: Too many entries returned (base: "OU=aaa,DC=abc,DC=com", filter: "(& (objectClass=organizationalUnit) (ou=测试部) )")
`
How should I use lsc to avoid this problem?

**Comment by wanglongsxr** [comment]
Here's the xml I'm currently using:
`
<?xml version="1.0" encoding="utf-8"?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldap://xxx:80/dc=abc,dc=com</url>
      <username>CN=xxxx,CN=xxx,DC=xxxx,DC=com</username>
      <password>111</password>
      <authentication>SIMPLE</authentication>  
      <referral>IGNORE</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>1000</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://xxxx:80/dc=def,dc=com</url>
      <username>cn=xxx,dc=def,dc=com</username>
      <password>2222</password>
      <authentication>SIMPLE</authentication>  
      <referral>THROW</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>-1</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ad"/>
          <baseDn>OU=aaa,DC=abc,DC=com</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="openldap"/>
        <baseDn>dc=def,dc=com</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=abc,DC=com";
          replace = "dc=def,dc=com";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>,</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>
`

**Comment by wanglongsxr** [comment]
Here's the xml I'm currently using:
`
<?xml version="1.0" encoding="utf-8"?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldap://xxx:80/dc=abc,dc=com</url>
      <username>CN=xxxx,CN=xxx,DC=xxxx,DC=com</username>
      <password>111</password>
      <authentication>SIMPLE</authentication>  
      <referral>IGNORE</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>1000</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://xxxx:80/dc=def,dc=com</url>
      <username>cn=xxx,dc=def,dc=com</username>
      <password>2222</password>
      <authentication>SIMPLE</authentication>  
      <referral>THROW</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>-1</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ad"/>
          <baseDn>OU=aaa,DC=abc,DC=com</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="openldap"/>
        <baseDn>dc=def,dc=com</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=abc,DC=com";
          replace = "dc=def,dc=com";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>,</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>
`

**Comment by wanglongsxr** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldap://xxx:80/dc=abc,dc=com</url>
      <username>xxxx</username>
      <password>111</password>
      <authentication>SIMPLE</authentication>  
      <referral>IGNORE</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>1000</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://xxxx:80/dc=def,dc=com</url>
      <username>xxx</username>
      <password>2222</password>
      <authentication>SIMPLE</authentication>  
      <referral>THROW</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>-1</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ad"/>
          <baseDn>OU=aaa,DC=abc,DC=com</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="openldap"/>
        <baseDn>dc=def,dc=com</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=abc,DC=com";
          replace = "dc=def,dc=com";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>,</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>
```

**Comment by wanglongsxr** [comment]
Here's the xml I'm currently using:
```xml
<?xml version="1.0" encoding="utf-8"?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldap://xxx:80/dc=abc,dc=com</url>
      <username>xxxx</username>
      <password>111</password>
      <authentication>SIMPLE</authentication>  
      <referral>IGNORE</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>1000</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://xxxx:80/dc=def,dc=com</url>
      <username>xxx</username>
      <password>2222</password>
      <authentication>SIMPLE</authentication>  
      <referral>THROW</referral>  
      <derefAliases>NEVER</derefAliases>  
      <version>VERSION_3</version>  
      <pageSize>-1</pageSize>  
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>  
      <tlsActivated>false</tlsActivated>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>ou-sync</name>
      <bean>org.lsc.beans.SimpleBean</bean>
      <ldapSourceService>
        <name>ou-sync-src</name>
        <connection reference="ad"/>
          <baseDn>OU=aaa,DC=abc,DC=com</baseDn>
          <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>distinguishedName</string>
          <string>ou</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit) )</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
        <cleanFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</cleanFilter>
      </ldapSourceService>
      <ldapDestinationService>
        <name>ou-sync-dst</name>
        <connection reference="openldap"/>
        <baseDn>dc=def,dc=com</baseDn>
        <pivotAttributes>
          <string>ou</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>ou</string>
          <string>objectClass</string>
        </fetchedAttributes>
        <getAllFilter>(&amp; (objectClass=organizationalUnit))</getAllFilter>
        <getOneFilter>(&amp; (objectClass=organizationalUnit) (ou={ou}) )</getOneFilter>
      </ldapDestinationService>
      <propertiesBasedSyncOptions>
        <mainIdentifier>
          var dn;
          var replace;
          var pattern;
          var regmask;

          dn = srcBean.getDatasetFirstValueById("distinguishedName");

          pattern= "DC=abc,DC=com";
          replace = "dc=def,dc=com";
          regmask = "gi";
          regex = new RegExp(pattern, regmask);
          dn = dn.replace(regex, replace);

          dn
        </mainIdentifier>
        <defaultDelimiter>,</defaultDelimiter>
        <defaultPolicy>FORCE</defaultPolicy>
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectClass</name>
          <policy>FORCE</policy>
          <forceValues>
            <string>"top"</string>
            <string>"organizationalUnit"</string>
          </forceValues>
          <delimiter>,</delimiter>
        </dataset>
        <dataset>
          <name>ou</name>
          <forceValues>
            <string>srcBean.getDatasetFirstValueById("ou")</string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>
```

**Comment by coudot** [comment]
Indeed LSC requires to match a single entry in source for an entry in destination.

There is no simple solution to your use case, here are some ideas:
* Store another attribute in destination entry, like the value of the parent branch in source, and use this a second pivot value
* Use LSC 2.2 (compile from sources) which introduces pivot transformation. You will be able to use the DN as pivot, with a rule to transform the value between source and destination: https://lsc-project.org/doku.php/documentation/2.2/configuration/syncoptions#pivot_transformation_lsc_tasks_task_propertiesbasedsyncoptions_pivottransformation

**Comment by wanglongsxr** [comment]
On the website you provided or on github, I didn't see the relevant 2.2 version. The latest version is 2.1.6
If there is a 2.2 version, can you provide me the link?
Thank you so much!

**Comment by coudot** [comment]
>  I didn't see the relevant 2.2 version

Build it from git master branch: https://github.com/lsc-project/lsc/tree/master

See also https://lsc-project.org/doku.php/documentation/latest/development/start#building
