### ISSUE TITLE
Need HELP!!   Empty or non existant source (no IDs found)

### ISSUE THREAD

**Issue by Chonghaolong** [lsc-project/lsc#211]
I used the example provided in the official document to do a test, and there was an error message after running, but I couldn't find what went wrong.
The Error information is:I
NFO  - Logging configuration successfully loaded from /etc/lsc/openldap2ad/logback.xml
Apr 07 00:12:04 - INFO  - LSC configuration successfully loaded from /etc/lsc/openldap2ad/
Apr 07 00:12:04 - INFO  - Connecting to LDAP server *:636/dc=*,dc=com as administrator@*.com
Apr 07 00:12:04 - INFO  - Connecting to LDAP server ldap://127.0.0.1:389/dc=*dc=com as cn=Manager,dc=*,dc=com
Apr 07 00:12:04 - ERROR - Empty or non existant source (no IDs found)
Apr 07 00:12:04 - INFO  - All entries: 5, to modify entries: 0, successfully modified entries: 0, errors: 0
Apr 07 00:12:05 - INFO  - All entries: 3, to modify entries: 0, successfully modified entries: 0, errors: 0
Apr 07 00:12:05 - INFO  - All entries: 27, to modify entries: 0, successfully modified entries: 0, errors: 0

**Comment by davidcoutadeur** [comment]
Hello,

Issues are for reporting bugs or asking features.

Please use the mailing list: https://lsc-project.org/doku.php/community

Also, if you have a problem, always provide your lsc.xml, else it is impossible to help you.

**Comment by Chonghaolong** [comment]
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldaps://WIN-7KLDOTPA6HG.chonghaolong.com:636/dc=chonghaolong,dc=com</url>  
      <username>administrator@chonghaolong.com</username>  
      <password>Chl136290.</password>  
      <authentication>SIMPLE</authentication>  
      <pageSize>1000</pageSize>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://127.0.0.1:389/dc=zszh,dc=com</url>  
      <username>cn=Manager,dc=zszh,dc=com</username>  
      <password>Aa123456</password>  
      <authentication>SIMPLE</authentication>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>a-PeopleSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <ldapSourceService>
        <name>openldap-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=people,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>displayName</string>
          <string>userPassword</string>  
          <string>objectClass</string>  
          <string>uid</string>  
          <string>mail</string>  
          <string>title</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=inetOrgPerson)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={uid}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={samAccountName}))]]></cleanFilter>
      </ldapSourceService>  
      <ldapDestinationService>
        <name>ad-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>samAccountName</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>objectClass</string>  
          <string>title</string>  
          <string>displayName</string>  
          <string>samAccountName</string>  
          <string>userPrincipalName</string>  
          <string>unicodePwd</string>  
          <string>pwdLastSet</string>  
          <string>userAccountControl</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=user)(sAMAccountName={user}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ", CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>
        <dataset>
          <name>description</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("sn").toUpperCase() + " (" + srcBean.getDatasetFirstValueById("mail") + ")"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>samAccountName</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>js:srcBean.getDatasetFirstValueById("uid")</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userPrincipalName</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("uid") + "@zszh.com"</string>
          </forceValues>
        </dataset>  
        <dataset>
          <name>objectClass</name>  
          <policy>FORCE</policy>  
          <createValues> 
            <string>"user"</string>  
            <string>"organizationalPerson"</string>  
            <string>"person"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userAccountControl</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>unicodePwd</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.getUnicodePwd("Chl136290.")</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>pwdLastSet</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"0"</string>
          </createValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
    <task>
      <name>b-GroupSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <asyncLdapSourceService>
        <name>group-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=Group,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>memberUid</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=posixGroup)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></cleanFilter>  
        <serverType>OpenLDAP</serverType>
      </asyncLdapSourceService>  
      <ldapDestinationService>
        <name>group-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>member</string>  
          <string>objectClass</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=group)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=group)(cn={cn}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>js:"cn=" + javax.naming.ldap.Rdn.escapeValue(srcBean.getDatasetFirstValueById("cn")) + ",CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectclass</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"group"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>
        <dataset>
          <name>member</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string> <![CDATA[
              rdjs:
                var membersSrcDn = srcBean.getAttributeValuesById("memberUid").toArray();
                var membersDstDn = [];

                for  (var i=0; i<membersSrcDn.length; i++) {
                  try {
                     membersSrcDn[i] = ldap.attribute(ldap.list("CN=Users","(sAMAccountName=" + (membersSrcDn[i]) + ")").get(0), 'distinguishedName').get(0)
                  } catch (e) {
                     membersSrcDn[i]=null;
                  }
                }
                var j=0;
                for (var i=0; i<membersSrcDn.length; i++) {
                  if (membersSrcDn[i]!=null) membersDstDn[j++]=membersSrcDn[i];
                }
                membersDstDn;
             ]]> </string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>

**Comment by Chonghaolong** [comment]
**this is my lsc.xml >** 
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldaps://WIN-7KLDOTPA6HG.chonghaolong.com:636/dc=chonghaolong,dc=com</url>  
      <username>administrator@chonghaolong.com</username>  
      <password>Chl136290.</password>  
      <authentication>SIMPLE</authentication>  
      <pageSize>1000</pageSize>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://127.0.0.1:389/dc=zszh,dc=com</url>  
      <username>cn=Manager,dc=zszh,dc=com</username>  
      <password>Aa123456</password>  
      <authentication>SIMPLE</authentication>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>a-PeopleSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <ldapSourceService>
        <name>openldap-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=people,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>displayName</string>
          <string>userPassword</string>  
          <string>objectClass</string>  
          <string>uid</string>  
          <string>mail</string>  
          <string>title</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=inetOrgPerson)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={uid}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={samAccountName}))]]></cleanFilter>
      </ldapSourceService>  
      <ldapDestinationService>
        <name>ad-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>samAccountName</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>objectClass</string>  
          <string>title</string>  
          <string>displayName</string>  
          <string>samAccountName</string>  
          <string>userPrincipalName</string>  
          <string>unicodePwd</string>  
          <string>pwdLastSet</string>  
          <string>userAccountControl</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=user)(sAMAccountName={user}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ", CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>
        <dataset>
          <name>description</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("sn").toUpperCase() + " (" + srcBean.getDatasetFirstValueById("mail") + ")"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>samAccountName</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>js:srcBean.getDatasetFirstValueById("uid")</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userPrincipalName</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("uid") + "@zszh.com"</string>
          </forceValues>
        </dataset>  
        <dataset>
          <name>objectClass</name>  
          <policy>FORCE</policy>  
          <createValues> 
            <string>"user"</string>  
            <string>"organizationalPerson"</string>  
            <string>"person"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userAccountControl</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>unicodePwd</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.getUnicodePwd("Chl136290.")</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>pwdLastSet</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"0"</string>
          </createValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
    <task>
      <name>b-GroupSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <asyncLdapSourceService>
        <name>group-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=Group,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>memberUid</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=posixGroup)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></cleanFilter>  
        <serverType>OpenLDAP</serverType>
      </asyncLdapSourceService>  
      <ldapDestinationService>
        <name>group-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>member</string>  
          <string>objectClass</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=group)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=group)(cn={cn}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>js:"cn=" + javax.naming.ldap.Rdn.escapeValue(srcBean.getDatasetFirstValueById("cn")) + ",CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectclass</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"group"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>
        <dataset>
          <name>member</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string> <![CDATA[
              rdjs:
                var membersSrcDn = srcBean.getAttributeValuesById("memberUid").toArray();
                var membersDstDn = [];

                for  (var i=0; i<membersSrcDn.length; i++) {
                  try {
                     membersSrcDn[i] = ldap.attribute(ldap.list("CN=Users","(sAMAccountName=" + (membersSrcDn[i]) + ")").get(0), 'distinguishedName').get(0)
                  } catch (e) {
                     membersSrcDn[i]=null;
                  }
                }
                var j=0;
                for (var i=0; i<membersSrcDn.length; i++) {
                  if (membersSrcDn[i]!=null) membersDstDn[j++]=membersSrcDn[i];
                }
                membersDstDn;
             ]]> </string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>

**Comment by Chonghaolong** [comment]
`<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0">  
  <connections>
    <ldapConnection>
      <name>ad</name>  
      <url>ldaps://WIN-7KLDOTPA6HG.chonghaolong.com:636/dc=chonghaolong,dc=com</url>  
      <username>administrator@chonghaolong.com</username>  
      <password>Chl136290.</password>  
      <authentication>SIMPLE</authentication>  
      <pageSize>1000</pageSize>
    </ldapConnection>  
    <ldapConnection>
      <name>openldap</name>  
      <url>ldap://127.0.0.1:389/dc=zszh,dc=com</url>  
      <username>cn=Manager,dc=zszh,dc=com</username>  
      <password>Aa123456</password>  
      <authentication>SIMPLE</authentication>
    </ldapConnection>
  </connections>  
  <tasks>
    <task>
      <name>a-PeopleSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <ldapSourceService>
        <name>openldap-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=people,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>uid</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>displayName</string>
          <string>userPassword</string>  
          <string>objectClass</string>  
          <string>uid</string>  
          <string>mail</string>  
          <string>title</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=inetOrgPerson)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={uid}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={samAccountName}))]]></cleanFilter>
      </ldapSourceService>  
      <ldapDestinationService>
        <name>ad-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>samAccountName</string>
        </pivotAttributes>
        <fetchedAttributes>
          <string>description</string>  
          <string>cn</string>  
          <string>sn</string>  
          <string>givenName</string>  
          <string>objectClass</string>  
          <string>title</string>  
          <string>displayName</string>  
          <string>samAccountName</string>  
          <string>userPrincipalName</string>  
          <string>unicodePwd</string>  
          <string>pwdLastSet</string>  
          <string>userAccountControl</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=user)(sAMAccountName={user}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ", CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>
        <dataset>
          <name>description</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("sn").toUpperCase() + " (" + srcBean.getDatasetFirstValueById("mail") + ")"</string>
          </forceValues>
        </dataset>
        <dataset>
          <name>samAccountName</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>js:srcBean.getDatasetFirstValueById("uid")</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userPrincipalName</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string>js:srcBean.getDatasetFirstValueById("uid") + "@zszh.com"</string>
          </forceValues>
        </dataset>  
        <dataset>
          <name>objectClass</name>  
          <policy>FORCE</policy>  
          <createValues> 
            <string>"user"</string>  
            <string>"organizationalPerson"</string>  
            <string>"person"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>  
        <dataset>
          <name>userAccountControl</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>unicodePwd</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>AD.getUnicodePwd("Chl136290.")</string>
          </createValues>
        </dataset>  
        <dataset>
            
          <name>pwdLastSet</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"0"</string>
          </createValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
    <task>
      <name>b-GroupSyncTask</name>  
      <bean>org.lsc.beans.SimpleBean</bean>  
      <asyncLdapSourceService>
        <name>group-source-service</name>  
        <connection reference="openldap"/>  
        <baseDn>ou=Group,dc=zszh,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>memberUid</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=posixGroup)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></getOneFilter>  
        <cleanFilter><![CDATA[(&(objectClass=posixGroup)(cn={cn}))]]></cleanFilter>  
        <serverType>OpenLDAP</serverType>
      </asyncLdapSourceService>  
      <ldapDestinationService>
        <name>group-dst-service</name>  
        <connection reference="ad"/>  
        <baseDn>cn=Users,dc=chonghaolong,dc=com</baseDn>  
        <pivotAttributes>
          <string>cn</string>
        </pivotAttributes>  
        <fetchedAttributes>
          <string>cn</string>  
          <string>description</string>  
          <string>member</string>  
          <string>objectClass</string>
        </fetchedAttributes>  
        <getAllFilter><![CDATA[(objectClass=group)]]></getAllFilter>  
        <getOneFilter><![CDATA[(&(objectClass=group)(cn={cn}))]]></getOneFilter>
      </ldapDestinationService>  
      <propertiesBasedSyncOptions>
        <mainIdentifier>js:"cn=" + javax.naming.ldap.Rdn.escapeValue(srcBean.getDatasetFirstValueById("cn")) + ",CN=Users,DC=chonghaolong,DC=com"</mainIdentifier>  
        <defaultDelimiter>;</defaultDelimiter>  
        <defaultPolicy>FORCE</defaultPolicy>  
        <conditions>
          <create>true</create>  
          <update>true</update>  
          <delete>false</delete>  
          <changeId>true</changeId>
        </conditions>  
        <dataset>
          <name>objectclass</name>  
          <policy>KEEP</policy>  
          <createValues>
            <string>"group"</string>  
            <string>"top"</string>
          </createValues>
        </dataset>
        <dataset>
          <name>member</name>  
          <policy>FORCE</policy>  
          <forceValues>
            <string> <![CDATA[
              rdjs:
                var membersSrcDn = srcBean.getAttributeValuesById("memberUid").toArray();
                var membersDstDn = [];

                for  (var i=0; i<membersSrcDn.length; i++) {
                  try {
                     membersSrcDn[i] = ldap.attribute(ldap.list("CN=Users","(sAMAccountName=" + (membersSrcDn[i]) + ")").get(0), 'distinguishedName').get(0)
                  } catch (e) {
                     membersSrcDn[i]=null;
                  }
                }
                var j=0;
                for (var i=0; i<membersSrcDn.length; i++) {
                  if (membersSrcDn[i]!=null) membersDstDn[j++]=membersSrcDn[i];
                }
                membersDstDn;
             ]]> </string>
          </forceValues>
        </dataset>
      </propertiesBasedSyncOptions>
    </task>
  </tasks>
</lsc>`

**Comment by Chonghaolong** [comment]
[lsc.txt](https://github.com/lsc-project/lsc/files/11177281/lsc.txt)
