### ISSUE TITLE
Empty or non existant source

### ISSUE THREAD

**Issue by Chonghaolong** [lsc-project/lsc#212]
I did a test with the example provided in the official documentation and there was an error message after running it, but I couldn't find what went wrong.
The error message is: I
NFO - Logging configuration successfully loaded from /etc/lsc/openldap2ad/logback.xml 07/00 12:04:2 - Info - LSC configuration successfully loaded from /etc/lsc/openldap07ad/
00/12 04:636:07 - Info - Connect to LDAP Server: 00/
dc=,dc=com as administrator@*
.com April 12 04:127:0 - Information - Connect to LDAP server ldap://0.1.389.07:00/dc=dc=com as cn=manager, dc=, dc=com
Dec 12 04:07:00 - Error - Source is empty or does not exist (ID not found)
12/04 5:0:0 - Info - All entries: 0, Entry to be modified: 07, Entry successfully modified: 00, Error: 12 Mar 05 3:0 - Info - All entries: 0, Entries modified: 0, Entries modified successfully: 07, Error: 00

12/05 27:<>:<> - Info - All entries: <>, Entry to modify: <>, Entry successfully modified: <>, Error: <>

MY lsc.xml is 
[lsc.txt](https://github.com/lsc-project/lsc/files/11177528/lsc.txt)

**Comment by davidcoutadeur** [comment]
As said before, issues are for reporting bugs or asking features.

Please use the mailing list: https://lsc-project.org/doku.php/community
