### ISSUE TITLE
Automatic build is broken

### ISSUE THREAD

**Issue by rouazana** [lsc-project/lsc#237]
Hello,

The Travis build is not available anymore. It's grey on [the main page](https://github.com/lsc-project/lsc) and there is no automatic build on the last pull requests. It makes me dubious merging the last pull requests.

**Comment by coudot** [comment]
Yes Travis can't be used anymore for free.

We need to set up github actions

**Comment by rouazana** [comment]
Ok thanks, I thought it was still available for Open Source: https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by coudot** [comment]
Yes but you need to ask for build credits and renew the operation everytime you need more.

See #238
