### ISSUE TITLE
Copy *all* values of an entry

### ISSUE THREAD

**Issue by kasimon** [lsc-project/lsc#24]
Am I correct that it is not possible to copy complete entries from one ldap server to another without having to specify all possible fields of the entries? I want to use lsc to migrate from one ldap server to another, and there are many different users and groups in the tree and I'd rather not specify all possible fields but just be able to tell lsc to copy what's there and maybe change a small set of fields while copying. If this should not be possible please consider this a feature request :)

**Comment by soisik** [comment]
Hi,

How did you come to this statement "it is not possible to copy complete entries from one ldap server to another without having to specify all possible fields of the entries" ?

LSC will synchronize only the attributes that you have configured to be synchronized in your lsc.xml 
https://lsc-project.org/documentation/2.0/configuration/service/sourceldap
https://lsc-project.org/documentation/2.0/configuration/service/destinationldap

So you can decide which attributes you wish to synchronize or not, and if necessary, you can also force values into some attribute. 

Please note, you will get more support from LSC community using the mailing list lsc-users@lists.lsc-project.org (register in https://lists.lsc-project.org/) rather than the bug tracker.

**Comment by kasimon** [comment]
Thanks for the pointer to the mailing list, I will post my question there too. To answer your Question: My intention is to sync a complete subtree of an LDAP directory with users, groups, nested ou's, special entiers for devices etc. to another ldap server (as part of a migration scenario from one ldap server software to another). My probably not very clearly statet question was, if lsc is the right tool to sync *all* entries with *all* fields from one server to another, without having to specify what is exactly ment by *all*, just sync everything that's there. This would be especially nice because it would allow a dry run comparison run after the migration to make sure everything was copied correctly.

**Comment by soisik** [comment]
Hi,

Thank you for clarifying. 

LSC cannot discover attributes set in a source entry and automatically synchronize them in destination entry, the mapping of src attributes to dest attributes is required, no matter if they are identical and don't need any transformation. 

Question is, are your source & destination LDAP servers the same distributions ? 

If they aren't the same distribution, you will need at some point to make some adaptations or transformations on the fly to meet the requirements of the new LDAP, and LSC is the right tool for it.

If they are the same distribution, why not considering standard LDAP backup & restore using LDIF format ?

**Comment by coudot** [comment]
Hello @kasimon, @soisik is right, LSC is not the right tool to do that. Indeed export/import with LDIF is right way to go. If you need to purge the LDIF data, you can look at this script: https://github.com/ltb-project/ldap-scripts/blob/master/convertldif.pl

**Comment by kasimon** [comment]
Hi @soisik and @coudot,

thanks for clarifying. I know how to export/import via ldif, I liked the idea of using lsc for it because it would allow the tree to be kept incrementally up to date during a transition phase, which would ease the process of switching those clients ovet to the new server that actually write data into ldap. But it's good to know that this is not ment to be possible with lsc, so I can test other options on how to do the migration. Thanks for the feedback and I'm sure there will be use cases for lsc for me in the future.

**Comment by coudot** [comment]
You can use LSC to sync your user entries or groups entries when the first import is done trough LDIF. I'm closing this issue.
