### ISSUE TITLE
 Cannot map binary value in dataset

### ISSUE THREAD

**Issue by soisik** [lsc-project/lsc#27]
On 01/11/2017 14:44, philipp.paeper@landkreis.lueneburg.de wrote:
> I try to sync our Active Directory with ApacheDS or 389-ds.
> I don't need the Password, just some user information.
> What I need is the attribute: "thumbnailPhoto" which is saved as binary/octed string in active directory.
> In the destination directory the attribute is named "imagePath". (I have to use a special scheme).
> 
> here is my ldapConnection for the AD:
> 
> <ldapConnection>
>       <name>ad-conn</name>
>       <url>ldap://dc.lklg.net:389/dc=lklg,dc=net</url>
>       <username>******</username>
>       <password>******</password>
>       <authentication>SIMPLE</authentication>
>       <referral>IGNORE</referral>
>       <derefAliases>NEVER</derefAliases>
>       <version>VERSION_3</version>
>       <pageSize>1000</pageSize>
>       <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
>       <tlsActivated>false</tlsActivated>
>       <binaryAttributes>
>         <string>thumbnailPhoto</string>
>       </binaryAttributes>
> </ldapConnection>
> 
> the ldapSourceService:
> 
> <ldapSourceService>
>         <name>ad-lklg-user-source-service</name>
>         <connection reference="ad-conn" />
>         <baseDn>ou=lklg-user,dc=lklg,dc=net</baseDn>
>         <pivotAttributes>
>           <string>sAMAccountName</string>
>         </pivotAttributes>
>         <fetchedAttributes>
>                 <string>mail</string>
>                 <string>employeeID</string>
>                 <string>displayName</string>
>                 <string>givenName</string>
>                 <string>sn</string>
>                 <string>title</string>
>                 <string>company</string>
>                 <string>department</string>
>                 <string>physicalDeliveryOfficeName</string>
>                 <string>streetAddress</string>
>                 <string>postalCode</string>
>                 <string>l</string>
>                 <string>st</string>
>                 <string>c</string>
>                 <string>wWWHomePage</string>
>                 <string>telephoneNumber</string>
>                 <string>homePhone</string>
>                 <string>mobile</string>
>                 <string>facsimileTelephoneNumber</string>
>                 <string>info</string>
>                 <string>thumbnailPhoto</string>
>                 <string>sAMAccountName</string>
>         </fetchedAttributes>
>         <getAllFilter>(&amp;(mail=*)(objectClass=user))</getAllFilter>
>         <getOneFilter>(&amp;(sAMAccountName={sAMAccountName})(objectClass=user))</getOneFilter>
>         <cleanFilter>(&amp;(sAMAccountName={sAMAccountName})(objectClass=user))</cleanFilter>
>       </ldapSourceService>
> 
> If I try to map the attribute in the propertiesBasedSyncOptions:
> 
>         <dataset>
>           <name>imagePath</name>
>           <policy>KEEP</policy>
>           <createValues>
>             <string>
>               srcBean.getDatasetFirstValueById("thumbnailPhoto")
>             </string>
>           </createValues>
>         </dataset>
> 
> The value is read as string (multiple value).
> Without a mapping (dataset config) the values are read as binary.
> 
> In the LscBeam doc (_https://lsc-project.org/javadoc/2.1-SNAPSHOT/org/lsc/beans/LscBean.html_) I don't see a possibility to read the values as binary.
> 
> Is there a way to sync binary values to a mapped attribute?

**Comment by nedy13** [comment]
We use a plugin as sync destination, but the ldap part remains. So you should be able to configure binaryAttributes.

https://lsc-project.org/documentation/2.1/configuration/connections/ldap?s[]=binaryAttributes

We uses this for objectGuid and objectSID attribute which is needed in our destination system.

Example conf:

```
<ldapConnection>
      <name>ldap-src-conn</name>
      <!--url>ldap://10.184.244.211:389/</url-->
	  <url>ldap://10.184.244.211:389/DC=CSM,DC=LAN</url>
	  <username>CN=srv_user,CN=Users,DC=csm,DC=lan</username>
      <password>***</password>
      <authentication>SIMPLE</authentication>
      <referral>IGNORE</referral>
      <derefAliases>NEVER</derefAliases>
      <version>VERSION_3</version>
      <pageSize>100000</pageSize>
      <factory>com.sun.jndi.ldap.LdapCtxFactory</factory>
      <tlsActivated>false</tlsActivated>
	<binaryAttributes>
                <string>objectGUID</string>
		<string>objectSID</string>
      </binaryAttributes>
    </ldapConnection>
```

Maybe it helps.

Regards,
Nedy

**Comment by nedy13** [comment]
I am not a developer..I am more a script kid, but my workmates implemented an own IWritableService and there you must write your own apply(LscModifications lm) method.
From the given LscModifications, we use lm.getModificationsItemsByHash(); and the properties "objectGuid" and "objectSID" are byte attributes in this case.

Regards
Nedy

**Comment by jeremypng** [comment]
Would it hurt to change the string that gets sent up by getDatasetValuesById in lscbean to send a Base64 encoded string instead of just calling the string function against the byte array?

something like this:
`if (value instanceof byte[]) {
						stringValue = new String(Base64.getEncoder().encodeToString(byte[] value));
						//stringValue = new String((byte[]) value);
					} else {
						stringValue = value.toString();
					}`
