### ISSUE TITLE
Debian postinst modifies installed scripts

### ISSUE THREAD

**Issue by go8ose** [lsc-project/lsc#273]
I noticed the postinst in the debian postinst script modifies /usr/bin/lsc, /usr/bin/lsc-agent and /usr/bin/hsqldb. That means the md5sums of those files from the package will not be correct.

I wondered if those files could be modified when the package is built, during the execution of the debian/rules file?

**Comment by davidcoutadeur** [comment]
I agree with you, it would be preferable to do the modification at the build step.

@xavierba for information: same issue here with the rpm packages.

**Comment by davidcoutadeur** [comment]
Should be ok with the last PR #274
