### ISSUE TITLE
getDatasetFirstValueById does not find attribute with an underscore

### ISSUE THREAD

**Issue by davidcoutadeur** [lsc-project/lsc#29]
for example, with plugin OBM:
Working code:
```
var nmail = dstBean.getDatasetFirstValueById("id");
```

Non working code:
```
var nmail = dstBean.getDatasetFirstValueById("nomad_mail");
```

I don't think it is linked to OBM plugin.

**Comment by coudot** [comment]
Hello @davidcoutadeur, I think this is because underscore is not valid in an LDAP attribute name (see https://docs.ldap.com/specs/rfc4512.txt)

Anyway, as in LSC we can have attributes that are not LDAP attributes, we must be able to read them.

**Comment by davidcoutadeur** [comment]
Bug not reproduced with the attribute mail_quota.
This bug is actually due to this one: https://github.com/lsc-project/lsc-obm-plugin/issues/1
The issue can be closed.
