### ISSUE TITLE
Using jdk 11 with LSC

### ISSUE THREAD

**Issue by albinscode** [lsc-project/lsc#312]
Hi there!

I'm an active user of the LSC solution and I'm using it for a long time with jdk 8.
I'm mainly deploying it on a debian 12. Are there any specific debian repository to use the jdk11 build?
Currently I'm building it on my own with the dedicated profile `mvn  package -Pjdk11` but that's only a workaround.

Thanks all for the good work ;)

**Comment by soisik** [comment]
Hi,
If your building from master branch you are using an unrelased/upstream version; This version is globally stable and hopefully we will find enough time to release it soon. 
The current official stable version available in our debian repository is v2.1 and it only supports jdk8.

**Comment by albinscode** [comment]
OK, thanks for your answer, by using a temurin 8 jdk we can gain some time.
