### ISSUE TITLE
Running LSC 2.1.4 with java 8 or java 9

### ISSUE THREAD

**Issue by fbarco** [lsc-project/lsc#33]
I want to use LSC on Ubuntu 16.04 server. This version provides openjdk-8-jre and openjdk-9-jre but LSC 2.1.4 returns some errors with these versions of java.
- With java 8 :
`ERROR - Fail to compute expression: "CN=" + java.lang.String(srcBean.getDatasetFirstValueById
Reason: javax.script.ScriptException: TypeError: java.lang.String is not a function in <eval> at line number 5`
- With java 9 :
`ERROR - Fail to compute expression: "CN=" + java.lang.String(srcBean.getDatasetFirstValueById
Reason: javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 3`

If i install openjdk-7-jre from ppa.launchpad.net, it works.

Is there any way to make it works with these versions of java ?

**Comment by coudot** [comment]
Why are you using java.lang.String? getDatasetFristValueById should already return a string.

**Comment by fbarco** [comment]
Thanks,
it works with java 8 if i modify lsc.xml like that :
- replace all `java.lang.String(srcBean.getData...` by `srcBean.getData...`
- replace `java.lang.reflect.Array.newInstance(java.lang.String, ...` by `java.lang.reflect.Array.newInstance(java.lang.String.class, ...`

But with java 9, i always have :
- `ERROR - Error while synchronizing ID {uid=[prenom.eleve304]}: org.lsc.exception.LscServiceException: javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 3`
- `ERROR - Fail to compute expression: "CN=" + srcBean.getDatasetFirstValueById(`
- `Reason: javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 3`

**Comment by coudot** [comment]
Can you try to set rjs: before the expression? See https://lsc-project.org/documentation/latest/scripting/start

**Comment by rouazana** [comment]
This line is too restrictive: https://github.com/lsc-project/lsc/blob/master/src/main/java/org/lsc/utils/JScriptEvaluator.java#L264
We must extend it to make it work with Java 9 too.

Feel free to provide a pull request!

**Comment by coudot** [comment]
Thanks @rouazana, we should fix this for 2.1.5

**Comment by fbarco** [comment]
I understand LSC will work with java 9 in version 2.1.5. I'm right ?

**Comment by rouazana** [comment]
see https://github.com/lsc-project/lsc/pull/94 for a fix on master.

**Comment by coudot** [comment]
LSC 2.1.5 will work with java <= 8 
LSC 2.2 will work with java >= 8
