### ISSUE TITLE
dependency-check result shows vulnerable dependencies in LSC

### ISSUE THREAD

**Issue by shiweiguo** [lsc-project/lsc#35]
Recent run dependency-check shows a number of vulnerable dependencies in the package, and recommended proposals are moving them to a newer version. e.g "Vulnerable Software & Versions:
cpe:/a:apache:directory_ldap_api:1.0.0:m30 and all previous versions" . Can these be fixed as early as possibile ? Thanks.

**Comment by shiweiguo** [comment]
can you share the target date for 2.1.5 ?

**Comment by coudot** [comment]
Hello @shiweiguo, there is no target date.

**Comment by coudot** [comment]
See #106

**Comment by coudot** [comment]
Closing this as duplicate of #106
