### ISSUE TITLE
DSID-030F18AE, problem 1006 (ATT_OR_VALUE_EXISTS)

### ISSUE THREAD

**Issue by akorn** [lsc-project/lsc#37]
Active Directory apparently doesn't allow you to replace a multivalued attribute set with a different set if the intersection of the two sets is not empty, giving the error above.

You have to delete the values you don't want/need with `changetype: modify`, `delete: attribute` operations, and add new ones separately.

Since lsc attempts `changetype: modify`, `replace: attribute`, it fails.

EDIT: I'm no longer certain this is the actual problem. I have some groups in AD with a multivalued `description:` attribute, but I can't seem to create new ones with more than one `description`, or change the descriptions of the existing ones unless the result is that they have exactly one `description` attribute.

**Comment by akorn** [comment]
(When talking to AD, it's probably safest to break down changes into individual operations; this also helps troubleshooting.)

**Comment by coudot** [comment]
Can you tell us on which attribute you have this behavior? This is a violation of LDAP protocol which clearly says that 'replace' in modification will drop old values to set new ones, whatever they are the same or not.

**Comment by akorn** [comment]
It was the `description` attribute.

I believe I drew the wrong conclusion from the error message. Like I wrote in the update, it seems that while it was possible to create groups with multiple `description`s before, AD won't allow it any longer. Any modification that impacts this attribute will be rejected unless the end result is that the entity has exactly one `description` remaining.

I'll chalk this one up to "AD is being AD".

However, I still believe there should be a way to ask lsc to perform minimal incremental changes to help with troubleshooting (AD error messages typically aren't very helpful). I'll file a new issue.
