### ISSUE TITLE
pivot attribute and clean filter unnecessary for LDAP; there are better ways

### ISSUE THREAD

**Issue by akorn** [lsc-project/lsc#39]
When synchronizing two LDAP backends, there is a 1:1 mapping between a source and a destination entity, and each entity has a uniqe ID, the DN.

LSC knows how to generate destination DNs from source DNs.

Instead of relying on the pivot attributes to find entities to remove during clean, lsc could keep track of what destination DNs it generated from source DNs, and remove the ones that exist but have not been thusly generated.

Alternatively, the user could provide the reverse mapping, from destination DN to source DN, and lsc could iterate over the destination DNs, generate the corresponding source DN, and clean the destination DN if the corresponding source DN doesn't exist.

I find the current solution, which relies on the pivot attributes and a separate clean filter, to be counter-intuitive and confusing.

**Comment by coudot** [comment]
From my point of view, it is the same to have a rule for the source DN that a filter for the clean search. And maybe the information to build the source DN is not available in destination entry. Having a filter on an attribute seems the clever option.
Another issue is that LSC works not only with LDAP directories, but also with databases. Using pivot attributes is compatible with both systems.

**Comment by rouazana** [comment]
An other issue is that you can have destination directory that are partially synced from source. So you may want to not remove every entry that are in the destination directory but not transformed from source entries.

**Comment by coudot** [comment]
Thanks for the suggestion, we may indeed need to improve performances, but using pivot is mandatory in some cases, we can't remove it like this.
