### ISSUE TITLE
Update locations in pom.xml

### ISSUE THREAD

**Issue by coudot** [lsc-project/lsc#5]
As we are moving code, issues, etc. the locations should be updated in pom.xml files

**Comment by coudot** [comment]
Done for master by commit 439e416ddb1e458ab59286ca0dc82c38b09141bb 

See also PR #6

**Comment by coudot** [comment]
Backported to branch 2.1 with cherry-pick commits

**Comment by rouazana** [comment]
> Backported to branch 2.1 with cherry-pick commits

Merging the merge commit did'nt work?

**Comment by coudot** [comment]
No because master branch was to far from 2.1. The best way would be to commit first on 2.1 branch then merge in master. I'll try to do that next time.
