### ISSUE TITLE
wiki : dead link to javadoc

### ISSUE THREAD

**Issue by nqb** [lsc-project/lsc#51]
Hello,

In wiki, when you follow links like this : http://lsc-project.org/javadoc/latest/org/lsc/utils/directory/AD.html#userAccountControlSet(int,%20java.lang.String[]), you get 404 error.

However, I you replace `latest` by `2.1-SNAPSHOT`, as seen in https://lsc-project.org/javadoc/, it works. 

See : https://lsc-project.org/javadoc/2.1-SNAPSHOT/org/lsc/utils/directory/AD.html#userAccountControlSet(int,%20java.lang.String[]

I notice `javadoc` dir modified last friday (2017-04-20), maybe a breaking change.

**Comment by coudot** [comment]
Thanks for the report, I recreated the 'latest' symlink.
