### ISSUE TITLE
option --version missing

### ISSUE THREAD

**Issue by nqb** [lsc-project/lsc#52]
Hello,

Currently in LSC, you don't have `--version` to know which version you used.
I see two solutions : 
* add a `--version` option
* print LSC's version when using `lsc -v`

**Comment by coudot** [comment]
Currently you can look at package version (for example dpkg -l | grep lsc)

**Comment by coudot** [comment]
We can grep the "version" option in bin/lsc and return the version from LSC core jar.

**Comment by artlog** [comment]
as  a warm-up i will work on this  one.

**Comment by artlog** [comment]
done, to review  ...
