### ISSUE TITLE
import users from openLdap to active directory 

### ISSUE THREAD

**Issue by universcom** [lsc-project/lsc#55]
Hi 
I have a openldap directory that i write my user into this directory. my environment have windows an linux that user with a  specific policy authenticated to windows that policies apply to users by gpo in active directory.
now i want sync openldap and active directory and each user registered in openldap(by my site) add to active directory. 
can lsc help me ?

**Comment by coudot** [comment]
Yes, see https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory

**Comment by universcom** [comment]
thank you very much ... very useful
