### ISSUE TITLE
https://lsc-project.org/svn/lsc-samples/lsc-embeddable-sample/trunk/  does not exists

### ISSUE THREAD

**Issue by onlinehack** [lsc-project/lsc#58]
wiki this link does not exists? 

https://lsc-project.org/svn/lsc-samples/lsc-embeddable-sample/trunk/

**Comment by coudot** [comment]
Indeed, SVN is no more available. All code is now on github, but the lsc-embeddable-sample no more exists.

I removed links from the wiki.
