### ISSUE TITLE
Why windows AD's Admininstrator User was deleted When openldap sync to AD

### ISSUE THREAD

**Issue by lklkxcxc** [lsc-project/lsc#61]
lsc version: lsc-2.1.4-0.el5.noarch

I just want to delete the non-existent user inside the OpenLDAP, but now delete all error and delete users of the system pages together.

Run “/usr/bin/lsc -f /etc/lsc/openldap2ad -s all -c all” command result delete  users,

but report error：

五月 24 09:46:50 - ERROR - Error while looking for 
                    (&(objectClass=inetOrgPerson)(uid=Administrator))
                 in ou=users,ou=RD,O=IT,dc=newhope,dc=com: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT'
五月 24 09:46:50 - ERROR - Error while synchronizing ID {samaccountname=Administrator}: org.lsc.exception.LscServiceException: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT'
五月 24 09:46:50 - ERROR - Unable to delete object CN=Administrator,CN=Users,DC=newhope,DC=com (org.lsc.exception.LscServiceException: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT')
.....................
五月 24 09:58:08 - ERROR - Error while looking for 
                    (&(objectClass=inetOrgPerson)(uid=test1))
                 in ou=users,ou=RD,O=IT,dc=newhope,dc=com: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT'
五月 24 09:58:08 - ERROR - Error while synchronizing ID {samaccountname=test1}: org.lsc.exception.LscServiceException: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT'
五月 24 09:58:08 - ERROR - Unable to delete object CN=test1,CN=Users,DC=newhope,DC=com (org.lsc.exception.LscServiceException: javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name 'ou=users,ou=RD,O=IT')
......................

config _lsc.xml  refrence https://lsc-project.org/documentation/tutorial/openldaptoactivedirectory:

> <propertiesBasedSyncOptions>
                <mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("cn") + ",cn=Users,dc=newhope,dc=com"</mainIdentifier>
                <defaultDelimiter>;</defaultDelimiter>
                <defaultPolicy>FORCE</defaultPolicy>
                <conditions>
                    <create>true</create>
                    <update>true</update>
                    <delete>true</delete>
                    <changeId>true</changeId>
                </conditions>
                <dataset>
                    <name>objectclass</name>
                    <policy>KEEP</policy>
                    <createValues>
                        <string>"user"</string>
                        <string>"organizationalPerson"</string>
                        <string>"top"</string>
                        <string>"person"</string>
                    </createValues>
                </dataset>
                <dataset>
                    <name>sAMAccountName</name>
                    <policy>KEEP</policy>
                    <createValues>
                        <string>srcBean.getDatasetFirstValueById("uid")</string>
                    </createValues>
                </dataset>
                <dataset>
                    
                    <name>userPrincipalName</name>
                    <policy>FORCE</policy>
                    <forceValues>
                        <string>srcBean.getDatasetFirstValueById("uid") + "@newhope.com"</string>
                    </forceValues>
                </dataset>
                <dataset>
                    <name>userAccountControl</name>
                    <policy>KEEP</policy>
                    <createValues>
                        <string>AD.userAccountControlSet( "0", [AD.UAC_SET_NORMAL_ACCOUNT])</string>
                    </createValues>
                </dataset>
                <dataset>
                   
                  <name>pwdLastSet</name>
                  <policy>KEEP</policy>
                  <createValues>
                     <string>"0"</string>
                  </createValues>
                </dataset>
                <dataset>
                  
                  <name>unicodePwd</name>
                  <policy>KEEP</policy>
                  <createValues>
                     <string>AD.getUnicodePwd("password")</string>
                  </createValues>
                </dataset>
            </propertiesBasedSyncOptions>

**Comment by coudot** [comment]
The error seems to say that the filter is bad, check the configuration of your LDAP filters.

**Comment by lklkxcxc** [comment]
@coudot I used LSC for the frist time,Please give me some prompt about filter?
