### ISSUE TITLE
Configuration of multiple plugin packages fails on Windows systems

### ISSUE THREAD

**Issue by dean-radish** [lsc-project/lsc#62]
Hello, configuring multiple plugin packages e.g

-DLSC.PLUGINS.PACKAGEPATH=foo.bar.plugins.configuration.file:foo.bar.plugins.configuration.ext

fails on Windows when using either a : or a ; path separator. The Unix separator ':' is hard coded in the JaxbXmlConfigurationHelper constructor, but System.getProperty("path.separator") is used later in the same class. Please make this consistent. 
Thanks
Dean

**Comment by coudot** [comment]
Thanks a lot @dean-radish for the patch. It has been applied in master and 2.1 branch
