### ISSUE TITLE
SSL/TLS configuration

### ISSUE THREAD

**Issue by franbuis** [lsc-project/lsc#63]
Hello, 
First, Thanks for this tool.
I tried to update an AD from an LDAP, it seems I need a certificat, but in your https://lsc-project.org/documentation/howto/ssltls I didn't find the line "$JAVA_HOME/bin/java -cp $CLASSPATH org.lsc.Launcher $*" to edit the shell script.
Did I miss something? Or something change since?
LDAP : OpenLDAPv3
AD : Windows 2016

Best regards,
Francis

**Comment by coudot** [comment]
If you use packages, the script is /usr/bin/lsc

The best is to export JAVA_OPTS env to add options

**Comment by franbuis** [comment]
Yes, I found the script but not the line inside.
But so, if i import the CA in JVM only, LSC will use it or i need to configure specifically for LSC in launcher?
I'm a bit lost :/

**Comment by coudot** [comment]
Of course, setting the AC inside JVM is the best way. LSC use the JVM so it will be able to use the CA registered in it.

**Comment by franbuis** [comment]
ok, nice I try this and tell u if it work for me.

**Comment by franbuis** [comment]
Hi, 

I got this message now with <tlsActivaded>true<tlsActivated>


juin 08 13:36:56 - ERROR - Error opening the LDAP connection to the
destination! (javax.net.ssl.SSLHandshakeException:
sun.security.validator.ValidatorExceptsun.security.provider.certpath.SunCertPathBuilderException:
unable to find valid certification path to requested target)
juin 08
13:36:56 - ERROR - org.lsc.exception.LscConfigurationException:
Configuration exception: javax.net.ssl.SSLHandshakeException:
sun.security.validator.ilding failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to
find valid certification path to requested target 

Bad certificat or he
didn't find it? 

Same with ldaps. :/ 

I test my CA with ldp.exe on
Windows and get a successful connexion with simple bind on SSL. 

Thx
for your support. 

Francis 

Le 2018-06-08 12:18, Clément OUDOT a écrit
: 

> Of course, setting the AC inside JVM is the best way. LSC use the
JVM so it will be able to use the CA registered in it. 
> 
> --
> You
are receiving this because you authored the thread.
> Reply to this
email directly, view it on GitHub [1], or mute the thread [2].



Links:
------
[1]
https://github.com/lsc-project/lsc/issues/63#issuecomment-395718059
[2]

**Comment by coudot** [comment]
The error indeed means that the CA certificate is not found in the JVM. Check with keytool that the CA is well registered

**Comment by franbuis** [comment]
Thx, I think the $JAVA_HOME are not well set, the admin must check-it and come back to me.

I tell u.


Francis

 

De : Clément OUDOT [mailto:notifications@github.com] 
Envoyé : vendredi 8 juin 2018 14:08
À : lsc-project/lsc
Cc : franbuis; Author
Objet : Re: [lsc-project/lsc] SSL/TLS configuration (#63)

 

The error indeed means that the CA certificate is not found in the JVM. Check with keytool that the CA is well registered

**Comment by franbuis** [comment]
Hello,
Ok, it's work now, first synchro create accounts but after some modifications (accountexpires for example) I have an error telling me that the account already exist so he doesn't update.

On my Ldap my pivot attribut is "uid" and on my AD my pivot Attribut is "cn", did i do Something wrong on my filter or my mainIdentifier?

Ldap : 
<getAllFilter><![CDATA[(&(objectClass=inetOrgPerson)(uvsqEmployeeCodeComposante=M))]]></getAllFilter>
<getOneFilter><![CDATA[(&(objectClass=inetOrgPerson)(uvsqEmployeeCodeComposante=M)(uid={uid}))]]></getOneFilter>
<cleanFilter><![CDATA[(&(objectClass=inetOrgPerson)(uid={cn}))]]></cleanFilter>

AD:
<getAllFilter><![CDATA[(objectClass=InetOrgPerson)]]></getAllFilter>
<getOneFilter><![CDATA[(&(objectClass=InetOrgPerson)(uid={cn}))]]></getOneFilter>


<mainIdentifier>"cn=" + srcBean.getDatasetFirstValueById("uid") + ",OU=Comptes,OU=Personnels,OU=I-MT,dc=me,dc=FR"</mainIdentifier>


Thanks for your help.

**Comment by coudot** [comment]
Your filter setttings in destination service may not be well configured.

See https://lsc-project.org/documentation/latest/basics

**Comment by franbuis** [comment]
Oh ok, I get it.
`<getAllFilter><![CDATA[(objectClass=user)]]></getAllFilter>
<getOneFilter><![CDATA[(&(objectClass=user)(cn={uid}))]]></getOneFilter>`
It's more like this.

**Comment by franbuis** [comment]
Ok, nice, I get an update in my console, but Nothing change in AD. The only thing he update is the UserAccountControl.
`juin 13 10:27:11 - INFO  - # Updating object CN=86369,ou=Comptes,ou=Personnels,ou=IT-M,dc=me,dc=fr for User-M-LdapToAD
# Wed Jun 13 10:27:11 CEST 2018
dn: CN=86369,ou=Comptes,ou=Personnels,ou=IT-M,dc=me,dc=fr
changetype: modify
replace: userAccountControl
userAccountControl: 66081` 

In the basics you says He read the fetchedattributes in src and Apply modifications if conditions are true.

If I delete the account he create him with the right value, but If i change he update only the UAC and again if I delete the new account will be ok;
It's my filter again? or an missing option ?

**Comment by coudot** [comment]
You need to define fetched attributes in source and destination to have them synced.

**Comment by franbuis** [comment]
Ah, I found it, It's the trick with ForceValue, Merge etc..

**Comment by franbuis** [comment]
I was only using <createValue> my bad

**Comment by franbuis** [comment]
So If i can abuse, when i use Policy KEEP with createValues He will only create value in AD the first time?
And If i want to update this values I need to use ForceValues instead with Policy Force?

**Comment by franbuis** [comment]
https://lsc-project.org/documentation/latest/configuration/syncoptions

**Comment by coudot** [comment]
Indeed, you found the documentation explaining it

**Comment by franbuis** [comment]
Thx, for your time :)
just one more question, it seems that the tasks are executed from the end of the lsc.xml file, it's me or normal process?

**Comment by coudot** [comment]
I think this is a random order if you call 'all' tasks. You can specify task name if you need a specific order.

**Comment by franbuis** [comment]
Yes, I use 'all' in my command line.
It's all good for me :)
Thx for your time  ^^b
