### ISSUE TITLE
LDAP / AD synchro change OU

### ISSUE THREAD

**Issue by franbuis** [lsc-project/lsc#64]
Hello,
How LSC while synchronizing can move an Object AD to Another OU?
If a user is in a group with the filter I can create him in the BaseDN "X", but if this user move to another how LSC can find him and move him to the other OU?
If i understand well, he use the mainidentifier to seek the values but Inside an OU set in stone.

Francis

**Comment by coudot** [comment]
You can use a javascript expression in mainIdentifier to set the branch were the entry should be moved. This requires to be able to deduce this branch from data in source directory.

**Comment by franbuis** [comment]
ouch, I will try to find some examples because it's more harder than i think. (i"m not a dev ;o) )
thx

**Comment by coudot** [comment]
Hope to have answered the question. Please reopen if needed
