### ISSUE TITLE
Order of task execution

### ISSUE THREAD

**Issue by dean-radish** [lsc-project/lsc#67]
When I have multiple tasks in a job then they execute in alphabetical order of the task name, not in the order defined in the XML. Is this expected behavior?
This happens if I use the  **all** keyword or a list of task names

**Comment by dean-radish** [comment]
See also https://lists.lsc-project.org/pipermail/lsc-users/2015-February/002492.html

**Comment by dean-radish** [comment]
I'm happy to create a pull request with a fix if you agree that they should execute in the order defined in the XML file

**Comment by coudot** [comment]
Why not, but you can also choose the order with lsc -s task1,task2,task3 ...

See https://lsc-project.org/documentation/latest/execution/start

**Comment by coudot** [comment]
We won't modify the default behavior but I will update documentation to better explain how to fix task order

**Comment by coudot** [comment]
Documentation updated

**Comment by davidcoutadeur** [comment]
Seems the task order is not enforced at all.

For example:

bin/lsc -f etc/ -sMySyncTask3,MySyncTask2,MySyncTask1 -t 1
```
juin 19 16:35:03 - INFO  - Starting sync for MySyncTask1
juin 19 16:35:04 - INFO  - All entries: 8, to modify entries: 0, successfully modified entries: 0, errors: 0
juin 19 16:35:04 - INFO  - Starting sync for MySyncTask2
juin 19 16:35:05 - INFO  - All entries: 8, to modify entries: 0, successfully modified entries: 0, errors: 0
juin 19 16:35:05 - INFO  - Starting sync for MySyncTask3
juin 19 16:35:05 - INFO  - All entries: 8, to modify entries: 0, successfully modified entries: 0, errors: 0
```

Seems the task order is determined by alpha-numeric sort of the task in lsc.xml

**Comment by coudot** [comment]
The order is now correctly set with the command line parameters. The order will never be the one of the lsc.xml file.
