### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by rmattes** [lsc-project/lsc#77]

**Comment by rmattes** [comment]
I just moved a sync setup to our production server and encounter a strange error. LSC complains about
"Your baseDn settings (ou=Personen,o=Hochschule für Musik,l=Freiburg,c=de) does not end with the LDAP naming context (o=Hochschule f?r Musik,l=Freiburg,c=de)."
Note the diffence in the organization part. The locale is set to 'en_US.UTF-8' (but changing this doesn't seem to make a difference). What magic switch/configuration option did I miss to get the LDAP naming context reported from the server interpreted in the correct encoding (the server _does_ report the correct naming context - it works in Python, PHP, Perl ...)

Strangely the login to the LDAP server succeeds (with a user DN under the given BaseDN).

**Comment by coudot** [comment]
Can you give the java version?

**Comment by rmattes** [comment]
Yes, this is on a Debian system:
 java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

I tried to install OpenJDK10 to test but lsc doesn't even start with that. BTW - the Debian package of lsc should probably depend on a JRE.

**Comment by rouazana** [comment]
you probably need to URL encode the naming context.
Then you probably will be able to let the baseDN as `ou=Personen` only.

**Comment by coudot** [comment]
Hope to have answered the question, please reopen if needed.
