### ISSUE TITLE
Confusing information about LDAP BaseDN

### ISSUE THREAD

**Issue by rmattes** [lsc-project/lsc#78]
When I configure and test-run lsc the program explicitly warns me about the BaseDN having to be a "full" DN value. But, according to my OpenLDAP server log, lsc appends the servers base naming context to this value (which, of course, is wrong).

**Comment by rouazana** [comment]
if the baseDN suffix is not exactly the same than the context, LSC will add the context. That's why you get a warning.

**Comment by coudot** [comment]
Hope to have answered the question, please reopen if needed.
