### ISSUE TITLE
js script will do not work with changing jdk7 to jdk8

### ISSUE THREAD

**Issue by vlepetit** [lsc-project/lsc#83]
Hi,

I use lsc to sync an OpenLdap (Supann schema) with an Active Directory.
For automatized AccountExpiration i used this dataset with this js script to calculate the user leaving date from our ldap ->

All this code is in production until more month and work fine. and work with java-7-openjdk-amd64 on my debian 7.11

Recently i have to develloped some code with Talend ETL and generate code who need java 8. So i installed jdk1.8.0_211 on my debian

After pass java 8 by default lsc return to me this error code for each user to sync

juin 21 08:44:27 - ERROR - Fail to compute expression: 
                                        var DateDepart = return_leavingdate(srcBean.getDatasetById("description").toArray());
                                        
                                        if (DateDepart != "9223372036854775807" ) AD.getAccountExpires(DateDepart ,"yyyyMMdd");
                                        else DateDepart;
                                         on id=uid=averdin,ou=people,dc=univ-psl,dc=fr
Reason: javax.script.ScriptException: TypeError: description.filter is not a function in <eval> at line number 19
juin 21 08:44:27 - ERROR - Error while synchronizing ID {uid=averdin}: org.lsc.exception.LscServiceException: javax.script.ScriptException: TypeError: description.filter is not a function in <eval> at line number 19

in my lsc.xml in task
------------------------------------------
<dataset>
                                <name>accountExpires</name>
                                <policy>FORCE</policy>
                                <forceValues>
                                         <string>js:
                                        var DateDepart = return_leavingdate(srcBean.getDatasetById("description").toArray());
                                        
                                        if (DateDepart != "9223372036854775807" ) AD.getAccountExpires(DateDepart ,"yyyyMMdd");
                                        else DateDepart;
                                        </string>
                                </forceValues>
                        </dataset>
                
                </propertiesBasedSyncOptions>
              	<scriptInclude>
    					<string>AccountExpirationDate.js</string>
  				</scriptInclude>

and the script js AccountExpirationDate.js 
----------------------------------------
function grep_leavingdate (description)
{
        var patterndepart = /{LEAVINGDATE}(.*)/;
        var trouvedepart = description.match(patterndepart);

        if (trouvedepart !== null ) return trouvedepart[1];
}

function grep_arrivaldate (description)
{
        var patternarrive = /{ARRIVALDATE}(.*)/;
        var trouvearrive = description.match(patternarrive);

        if (trouvearrive !== null ) return trouvearrive[1];
}

function return_leavingdate(description)
{
var descriptionfiltreDatesDeparts = description.filter(grep_leavingdate);

var descriptionfiltreDatesArrives = description.filter(grep_arrivaldate);

var DatesDepart = descriptionfiltreDatesDeparts.map(grep_leavingdate);

var DatesArrive = descriptionfiltreDatesArrives.map(grep_arrivaldate);

var DateDepartMax = Math.max.apply(null,DatesDepart);

var DateArriveMax = Math.max.apply(null,DatesArrive);

// convertion de la date depart max au bon format pour le calcul
var DateDepartMaxString = DateDepartMax.toString();
var AnneeDepartMax = DateDepartMaxString.substring(0,4);
var MoisDepartMax = DateDepartMaxString.substring(4,6)-1; //car valeur basée sur 0 janvier = 0
var JourDepartMax = DateDepartMaxString.substring(6,8);

var DateAccountExpiration = new Date(AnneeDepartMax,MoisDepartMax,JourDepartMax);

DateAccountExpiration.setDate(DateAccountExpiration.getDate() + 1);// la date expiration est le lendemain de date departmax

var AnneeDateAccountExpiration = DateAccountExpiration.getFullYear();
var MoisDateAccountExpiration = DateAccountExpiration.getMonth()+1;// getMonth() is zero-based
var JourDateAccountExpiration = DateAccountExpiration.getDate();

// on reconstitut la date d expiration au format yyyymmdd
var DateAccountExpirationString = [AnneeDateAccountExpiration,
								    (MoisDateAccountExpiration>9 ? '' : '0') + MoisDateAccountExpiration,
								    (JourDateAccountExpiration>9 ? '' : '0') + JourDateAccountExpiration
								   ].join('');

//si pas de date depart ou si arrive > depart renvoi code ms never
if ((DateDepartMax > DateArriveMax)&&(DateDepartMax != "-Infinity")) return DateAccountExpirationString;
else return "9223372036854775807" ;
}

/* debug
 
var description = ["{ARRIVALDATE}20180905","{LEAVINGDATE}20180930"];

var DateAccountExpiration = return_leavingdate(description);

console.log(DateAccountExpiration.toString());
*/
----------------------------------------------------------

What the different between java 7 and java 8 ? it's seem to be a problem with variable scope in js function.
Have you an idear ?

Regards,
vlepetit

**Comment by soisik** [comment]
This is because JS script engine has changed between the two version, and the "toArray()" on a java.util.Set does not return a javascript array as it used to in JDK 7.

This is what happen when trying to run the faulty line in java 8 js engine, and a workaround to convert the java Set to javascript Array:
```
$ $JAVA_HOME/bin/jjs
jjs> var array = new java.util.HashSet();
jjs> array.add('someText');
true
jjs> array.toArray().filter(function test() {return true});
<shell>:1 TypeError: array.toArray().filter is not a function
jjs> Java.from(array).filter(function test() {return true});
someText
```
Try to replace:
`var DateDepart = return_leavingdate(srcBean.getDatasetById("description").toArray());`
By:
`var DateDepart = return_leavingdate(Java.from(srcBean.getDatasetById("description")));`

**Comment by vlepetit** [comment]
Great !! it's seem to work..

thank you !

vlepetit
