### ISSUE TITLE
need more details on lsc.status like task and phase 

### ISSUE THREAD

**Issue by gallak** [lsc-project/lsc#90]
I think that lsc.status loose some informations because is shows only summary of modified entries or errors.

It should be useful to have more details like
number of entries, modified entries, deleted entries per task and phase

I suggest  this kind of output :
```
sept. 12 12:10:50 - INFO  - All entries: 197, to modify entries: 0, successfully modified entries: 0, errors: 0 - task : sync A-firstTask 
sept. 12 12:10:50 - INFO  - All entries: 197, to modify entries: 1, successfully deleted entries: 1, errors: 0 - task : clean A-firstTask 
sept. 12 12:10:50 - INFO  - All entries: 150, to modify entries: 4, successfully modified entries: 3, errors: 1 - task : sync B-secondTask 
```

as a consequence , nagios script should modified with the following syntax : 
check_lsc_status_file.pl -l /path/of/file -t <taskname> -syncw <warn level for sync phase of taskname> -syncc <critical level for sync phase of taskname>  -cleanw <warn level for clean phase of taskname>  -cleanc <critical level for clean phase of taskname> -f  ...

for example 
2 task like A-firstTask  with sync and clean phase and B-secondTask with only sync phase

```
check_lsc_status_file.pl \
-l /var/log/lsc/lsc.status \
-t A-firstTask \
-syncw 0 \
-syncc 0 \
-cleanw 0 \
-cleanc 0 \
-t B-secondTask \
-syncw 0 \
-syncc 0 \
-f  ... 
```

Task name should be followed at least by 2 values of critical and warning level for sync or clean phase.

The response  could be : 
`WARN - LSC is running with some errors (A-FirstTask, SW=0,SC=0,CS=0,CC=0/ B-SecondTask, SW=0,SC=0|'A_FirstTask__all'=197 'A_FirstTask__SW'=0 'A_FirstTask__SC'=0 'A_FirstTask__CW'=0 'A_FirstTask__CC'=0;0;0 |'B_SecondTask__all'=150 'B_SecondTask__SW'=0 'B_SecondTask__SC'=0 ;1`

**Comment by gallak** [comment]
as suggest by mail : https://github.com/lsc-project/lsc/pull/53#issuecomment-385384627
It do the same job but it is more expensive  ( one reading versus one reading per phase per task)

**Comment by coudot** [comment]
This will be done with #53

**Comment by coudot** [comment]
See #302
