### ISSUE TITLE
Insecure temp file creation

### ISSUE THREAD

**Issue by linnea-s** [lsc-project/lsc#95]
The sample configuration and scripts write many files to /tmp, as can be seen with fgrep -r /etc lsc. In particular bin/lsc and and etc/logback.xml, which are probably used unchanged by many users following the instructions on the website. These temporary files have known, fixed names.  This is insecure and can lead to information disclosure or overwriting of files by another user on the system. See e.g. https://cwe.mitre.org/data/definitions/377.html

I suggest defaulting to writing logs to LSC_HOME, and using a secure method for creating temporary files and directories.

**Comment by coudot** [comment]
The log directory is already changed in packages (RPM/Debian).

It could indeed be changed in the source code.

**Comment by coudot** [comment]
This requires changes in bin/lsc and logback.xml

**Comment by coudot** [comment]
Packaging files must also be updated

**Comment by davidcoutadeur** [comment]
In debian packages, I have not found in reference to tmp directory in `/usr/bin/lsc`, nor `/etc/lsc/*`
Maybe this problem is only present in source files.

**Comment by coudot** [comment]
Proposed solution: create a randon tmp dir (`mktemp` with lsc prefix) for LOG_DIR. But LOG_DIR will still be overridden in RPM and DEB.

**Comment by davidcoutadeur** [comment]
Not so trivial.

LOG_DIR in bin/lsc is used only for logging start and end of lsc run.

The main problem is to fix logback.xml:

```
<property name="logdir" value="/tmp/lsc/log" />
```

I am working on this.

**Comment by davidcoutadeur** [comment]
Done in 77ff84bf
